### ISSUE TITLE
Distributed NAF agent fails to initialize

### ISSUE THREAD

**Issue by admcl** [reinforceio/tensorforce#113]
I'm getting an Attribute error while trying to configure my NAF agent:
```
nafConfig = Configuration.from_json('naf_agent.json') #Copied from examples.

net = layered_network_builder([dict(type='dense', size=512, activation='tanh'), \
                               dict(type='dense', size=512, activation='tanh'), \
                               dict(type='dense', size=512, activation='sigmoid') \
    ])

nafConfig.default(dict(states=environment.states, actions=environment.actions, network=net))

nafConfig.default(dict(distributed=True, cluster_spec=cluster_spec, global_model=(rank == 0), device=('/job:ps' if rank == 0 else '/job:worker/task:{}/cpu:0'.format(rank))))

agent = NAFAgent(config=nafConfig)
```
...Produces the following problem on each node:
```
Traceback (most recent call last):
  File "/home/admcl/NAF_async.py", line 113, in <module>
    agent = NAFAgent(config=nafConfig)
  File "/net/fs01.cluster.com/home/admcl/tensorforce/tensorforce/agents/memory_agent.py", line 62, in __init__
    super(MemoryAgent, self).__init__(config, model)
  File "/net/fs01.cluster.com/home/admcl/tensorforce/tensorforce/agents/agent.py", line 156, in __init__
    self.model = self.__class__.model(config)
  File "/net/fs01.cluster.com/home/admcl/tensorforce/tensorforce/models/naf_model.py", line 45, in __init__
    super(NAFModel, self).__init__(config)
  File "/net/fs01.cluster.com/home/admcl/tensorforce/tensorforce/models/q_model.py", line 48, in __init__
    super(QModel, self).__init__(config)
  File "/net/fs01.cluster.com/home/admcl/tensorforce/tensorforce/models/model.py", line 96, in __init__
    self.global_model = self.__class__(config=global_config)
  File "/net/fs01.cluster.com/home/admcl/tensorforce/tensorforce/models/naf_model.py", line 45, in __init__
    super(NAFModel, self).__init__(config)
  File "/net/fs01.cluster.com/home/admcl/tensorforce/tensorforce/models/q_model.py", line 51, in __init__
    self.possible_update_target(force=True)
  File "/net/fs01.cluster.com/home/admcl/tensorforce/tensorforce/models/q_model.py", line 173, in possible_update_target
    self.session.run(self.target_network_update)
AttributeError: 'NoneType' object has no attribute 'run'
```

**Comment by michaelschaarschmidt** [comment]
As discussed in Gitter, the standard distributed mode probably does not make sense to be combined with NAF, we would have to consider implementing distributed q models via shared memory, so I will close this for now
