### ISSUE TITLE
Async w/ DQNAgent: 'NoneType' object has no attribute 'run' (self.session)

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#120]
When I run `python examples/openai_gym_async.py Pong-ram-v0 -a VPGAgent -c examples/configs/vpg_agent.json -n examples/configs/vpg_network.json -w 3 -D` and tmux in with `tmux a -t openai_async`, all's running smoothly. If I use DQNAgent configs instead:

`python examples/openai_gym_async.py Pong-ram-v0 -a DQNAgent -c examples/configs/dqn_agent.json -n examples/configs/dqn_network.json -w 3 -D`

then I get 

```bash
CUDA_VISIBLE_DEVICES= /home/lefnire/anaconda3/envs/btc3/bin/python /home/lefnire/Sites/btc/tmp/tensorforce/examples/openai_gym_async.py Pong-ram-v0 --is-child --agent DQNAgent --agent-config /home/lefnire/Sites/btc/tmp/tensorforce/examples/configs/dqn_agent.json --network-config /home/lefnire/Sites/btc/tmp/tensorforce/examples/configs/dqn_network.json --num-workers 3 --task-index -1 --debug
(btc3) lefnire@lefnire-ubuntu:~/Sites/btc/tmp/tensorforce$ CUDA_VISIBLE_DEVICES= /home/lefnire/anaconda3/envs/btc3/bin/python /home/lefnire/Sites/btc/tmp/tensorforce/examples/openai_gym_async.py Pong-ram-v0 --is-child --agent DQNAgent --agent-config /home/lefnire/Sites/btc/tmp/tensorforce/examples/configs/dqn_agent.json --network-config /home/lefnire/Sites/btc/tmp/tensorforce/examples/configs/dqn_network.json --num-workers 3 --task-index -1 --debug
[2017-09-07 13:28:12,300] Making new env: Pong-ram-v0
Traceback (most recent call last):
  File "/home/lefnire/Sites/btc/tmp/tensorforce/examples/openai_gym_async.py", line 182, in <module>
    main()
  File "/home/lefnire/Sites/btc/tmp/tensorforce/examples/openai_gym_async.py", line 151, in main
    agent = agents[args.agent](config=agent_config)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/agents/memory_agent.py", line 62, in __init__
    super(MemoryAgent, self).__init__(config, model)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/agents/agent.py", line 162, in __init__
    self.model = self.__class__.model(config)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/dqn_model.py", line 48, in __init__
    super(DQNModel, self).__init__(config)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/q_model.py", line 51, in __init__
    self.possible_update_target(force=True)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/q_model.py", line 173, in possible_update_target
    self.session.run(self.target_network_update)
AttributeError: 'NoneType' object has no attribute 'run'
```

**Comment by michaelschaarschmidt** [comment]
Please see https://github.com/reinforceio/tensorforce/issues/113 for details

Distributed DQN with A3C semantics does not make sense, so it's not supported

**Comment by lefnire** [comment]
Gotcha, makes sense.

**Comment by michaelschaarschmidt** [comment]
If you want something closely related please look at the n-step DQN agent (and maybe check the A3C paper) and the multithreaded example

**Comment by lefnire** [comment]
I'll give that a shot, thanks! So from what I understand PolicyGradientModels are the ones that make sense for A3C (or special cases like n-step DQN) - may need to update:

```diff
diff --git a/tensorforce/execution/runner.py b/tensorforce/execution/runner.py
index 906522f..5cd21d7 100644
--- a/tensorforce/execution/runner.py
+++ b/tensorforce/execution/runner.py
@@ -33,7 +33,7 @@ from tensorforce import TensorForceError
 class Runner(object):
 
     # These agents can be used in an A3C fashion
-    async_supported = ('VPGAgent', 'DQNAgent', 'NAFAgent')
+    async_supported = ('VPGAgent', 'PPOAgent', 'TRPOAgent')
 
     def __init__(self, agent, environment, repeat_actions=1, cluster_spec=None, task_index=None, save_path=None, save_episodes=None):
         """
```

**Comment by AlexKuhnle** [comment]
Yes, although I'm not quite sure about TRPO in the current state (but it should, yes). It's still something we need to look more into, haven't really checked performance so far, for instance.
