### ISSUE TITLE
 multiple actions did not work!

### ISSUE THREAD

**Issue by aGiant** [reinforceio/tensorforce#143]
Hi guys,
i have defined agent like this:
config = Configuration(
    batch_size=240,
    states=dict(shape=(len(cols),), type='float'),
    actions=dict(continuous=True, num_actions=4),
    network=layered_network_builder([dict(type='dense', size=50), dict(type='dense', size=50)])
)

but the output of act had only one value instead of 4:
act = agent.act(state=state.values[0])
print "act = ", act

Output: act =  1.00661

Can anyone here tell me how to get it work? Thanks

**Comment by AlexKuhnle** [comment]
Hi @aGiant,
The parameter `num_actions` does only work for discrete actions and here specifies how many discrete alternatives one such discrete action has. For both discrete and continuous actions, you can instead specify the `shape` parameter (default: `()`) to get the number and shape of actions you want, so in your case: `dict(continuous=True, shape=(4,))`.
Hope that works better!

**Comment by aGiant** [comment]
I had tried 
actions = dict(continuous=True, shape=(4,))
but got more errors:
Traceback (most recent call last):
  File "/home/llu/Data/tensorforce_trading.py", line 50, in <module>
    act = agent.act(state=state.values[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/agent.py", line 221, in act
    self.current_action, self.next_internal = self.model.get_action(state=self.current_state, internal=self.current_internal, deterministic=deterministic)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 248, in get_action
    fetched = self.session.run(fetches=fetches, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas GEMM launch failed : a.shape=(1, 1117), b.shape=(1117, 50), m=1, n=50, k=1117
	 [[Node: value_function/dense0/linear/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_placeholder/state_0_1/_1, value_function/dense0/linear/W/read)]]
	 [[Node: distribution/Select/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_68_distribution/Select", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'value_function/dense0/linear/MatMul', defined at:
  File "/home/llu/Data/tensorforce_trading.py", line 39, in <module>
    agent = TRPOAgent(config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/batch_agent.py", line 55, in __init__
    super(BatchAgent, self).__init__(config, model)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/agent.py", line 162, in __init__
    self.model = self.__class__.model(config)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/trpo_model.py", line 55, in __init__
    super(TRPOModel, self).__init__(config)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/policy_gradient_model.py", line 89, in __init__
    super(PolicyGradientModel, self).__init__(config)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 112, in __init__
    self.create_tf_operations(config)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/trpo_model.py", line 68, in create_tf_operations
    super(TRPOModel, self).create_tf_operations(config)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/policy_gradient_model.py", line 96, in create_tf_operations
    self.network = NeuralNetwork(network_builder=network_builder, inputs=self.state)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/networks/network.py", line 37, in __init__
    network = network_builder(inputs, summary_level=summary_level)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/networks/layers.py", line 355, in network_builder
    kwargs=dict(x=x, scope=scope, summary_level=summary_level)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/util.py", line 173, in get_object
    return obj(**full_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/networks/layers.py", line 220, in dense
    x = linear(x=x, size=size, bias=bias, l2_regularization=l2_regularization, l1_regularization=l1_regularization)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/networks/layers.py", line 181, in linear
    x = tf.matmul(a=x, b=weights)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1844, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1289, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(1, 1117), b.shape=(1117, 50), m=1, n=50, k=1117
	 [[Node: value_function/dense0/linear/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_placeholder/state_0_1/_1, value_function/dense0/linear/W/read)]]
	 [[Node: distribution/Select/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_68_distribution/Select", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by AlexKuhnle** [comment]
This looks like a TensorForce-unrelated problem to me: *"Blas GEMM launch failed"* etc. Have you googled what such an exception in TensorFlow? (Are you running the distributed mode?)

**Comment by aGiant** [comment]
Got it! Someone has used all GPUs. It works now and Thanks very much!!
