### ISSUE TITLE
Can't use double_dqn=True w/ DQNNstepAgent

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#155]
I'll take the Gittr convo here, pretty sure it's a bug. Simple copy/paste of quickstart.py:

```python
from tensorforce import Configuration
from tensorforce.agents import DQNNstepAgent
from tensorforce.core.networks import layered_network_builder
from tensorforce.execution import Runner
from tensorforce.contrib.openai_gym import OpenAIGym

env = OpenAIGym('CartPole-v0')
agent = DQNNstepAgent(
    Configuration(
    states=env.states,
    actions=env.actions,
    batch_size=8,
    double_dqn=True,
    network=layered_network_builder([dict(type='dense', size=32)])
))

runner = Runner(agent=agent, environment=env)
def episode_finished(r):
    print(r.episode_rewards[-1])
    return True

runner.run(episodes=3000, max_timesteps=200, episode_finished=episode_finished)
```

If you run it like that, you get:

```shell
Traceback (most recent call last):
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'placeholder_1/state' with dtype float and shape [?,4]
         [[Node: placeholder_1/state = Placeholder[dtype=DT_FLOAT, shape=[?,4], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: target/action/Sum/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_61_target/action/Sum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart2.py", line 23, in <module>
    runner.run(episodes=3000, max_timesteps=200, episode_finished=episode_finished)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/execution/runner.py", line 149, in run
    self.agent.observe(reward=reward, terminal=terminal)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/agents/batch_agent.py", line 89, in observe
    self.model.update(self.batch)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/q_model.py", line 166, in update
    return super(QModel, self).update(*args, **kwargs)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/model.py", line 273, in update
    feed_dict = self.update_feed_dict(batch=batch)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/dqn_nstep_model.py", line 66, in update_feed_dict
    target_q_vals = self.session.run(self.target_values, feed_dict=feed_dict)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'placeholder_1/state' with dtype float and shape [?,4]
         [[Node: placeholder_1/state = Placeholder[dtype=DT_FLOAT, shape=[?,4], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: target/action/Sum/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_61_target/action/Sum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'placeholder_1/state', defined at:
  File "quickstart2.py", line 15, in <module>
    network=layered_network_builder([dict(type='dense', size=32)])
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/agents/batch_agent.py", line 55, in __init__
    super(BatchAgent, self).__init__(config, model)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/agents/agent.py", line 162, in __init__
    self.model = self.__class__.model(config)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/dqn_model.py", line 48, in __init__
    super(DQNModel, self).__init__(config)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/q_model.py", line 48, in __init__
    super(QModel, self).__init__(config)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/model.py", line 112, in __init__
    self.create_tf_operations(config)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/dqn_nstep_model.py", line 45, in create_tf_operations
    super(DQNNstepModel, self).create_tf_operations(config)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/q_model.py", line 54, in create_tf_operations
    super(QModel, self).create_tf_operations(config)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/model.py", line 196, in create_tf_operations
    self.state[name] = tf.placeholder(dtype=util.tf_dtype(state.type), shape=(None,) + tuple(state.shape), name=name)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1548, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2094, in _placeholder
    name=name)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'placeholder_1/state' with dtype float and shape [?,4]
         [[Node: placeholder_1/state = Placeholder[dtype=DT_FLOAT, shape=[?,4], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
         [[Node: target/action/Sum/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_61_target/action/Sum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

```

But if you comment out `double_dqn=True`, it runs fine. Incidentally a `batch_size` > 1 is required, else you get 

```shell
Traceback (most recent call last):
  File "quickstart2.py", line 23, in <module>
    runner.run(episodes=3000, max_timesteps=200, episode_finished=episode_finished)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/execution/runner.py", line 149, in run
    self.agent.observe(reward=reward, terminal=terminal)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/agents/batch_agent.py", line 89, in observe
    self.model.update(self.batch)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/q_model.py", line 166, in update
    return super(QModel, self).update(*args, **kwargs)
  File "/home/lefnire/Sites/btc/tmp/tensorforce/tensorforce/models/model.py", line 284, in update
    returns = self.session.run(fetches=fetches, feed_dict=feed_dict)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor 'placeholder_1/state:0', which has shape '(?, 4)'
```

I'm wondering if the they're related? Maybe there's some sensitive combo of `batch_size`, `memory_capacity`, `first_update`, `target_update_frequency` or the like when using DQNNstep? I'll do some step-debugging myself (hope to start contributing), but dropping here in case y'all have a "oh I know what that is.."

**Comment by lefnire** [comment]
Looks like `dqn_nstep_model#update_feed_dict`'s feed_dict needs `state` as well as `next_state`. This solves the crashing, but I'm not sure if the idea, or at least the array-indexing, is correct:

```diff
diff --git a/tensorforce/models/dqn_nstep_model.py b/tensorforce/models/dqn_nstep_model.py
index 8ba2f4b..fa3c1f0 100644
--- a/tensorforce/models/dqn_nstep_model.py
+++ b/tensorforce/models/dqn_nstep_model.py
@@ -61,6 +61,7 @@ class DQNNstepModel(DQNModel):
         # assume temporally consistent sequence
         # get state time + 1
         feed_dict = {next_state: [batch['states'][name][-1]] for name, next_state in self.next_state.items()}
+        feed_dict.update({state: [batch['states'][name][-1]] for name, state in self.state.items()})
         feed_dict.update({internal: [batch['internals'][n][-1]] for n, internal in enumerate(self.next_internal_inputs, self.network_internal_index)})
         # calcualte nstep rewards
         target_q_vals = self.session.run(self.target_values, feed_dict=feed_dict)
```

(Copied from [q_model#update_feed_dict](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/q_model.py#L154))

**Comment by Islandman93** [comment]
@lefnire This is the correct fix, good catch. Double dqn uses the online network's estimated action (in state t+1, which is why the [-1] is needed) to calculate the target values. So we need the state placeholder to get the estimated action. I wonder for regular dqn if this line has any affect on performance or if tensorflow just ignores it since it's not needed.

A batchsize of 1 won't work since we always need the state t+1, but a better error is a good idea.

**Comment by AlexKuhnle** [comment]
This should work in the dev branch as well, but if not, feel free to re-open.
