### ISSUE TITLE
DQNAgent: AttributeError: 'Beta' object has no attribute 'state_action_value'

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#174]
Trying to use DQNAgent in #dev results in the following error. Culprit being [tf_q_value](https://github.com/reinforceio/tensorforce/blob/903dde381faa12b19643817b3428e93d3eb830e1/tensorforce/models/q_model.py#L64), comment indicates the line's specialized for NAF, maybe causes problems with vanilla Q?

```shell
(btc3) lefnire@lefnire-ubuntu:~/Sites/btc$ python tforce/single.py 
[2017-10-18 11:54:26,451] Making new env: BTC-v0
2017-10-18 11:54:26.530395: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-10-18 11:54:26.530617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.90GiB freeMemory: 3.65GiB
2017-10-18 11:54:26.530626: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "tforce/single.py", line 15, in <module>
    env_args=dict(is_main=True)
  File "/home/lefnire/Sites/btc/agent_conf.py", line 385, in conf
    config=conf
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/agents/dqn_agent.py", line 159, in __init__
    super(DQNAgent, self).__init__(states_spec, actions_spec, config)
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/agents/memory_agent.py", line 51, in __init__
    super(MemoryAgent, self).__init__(states_spec, actions_spec, config)
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/agents/agent.py", line 177, in __init__
    config=config
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/agents/dqn_agent.py", line 166, in initialize_model
    config=config
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/models/q_model.py", line 52, in __init__
    config=config
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/models/distribution_model.py", line 98, in __init__
    config=config
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/models/model.py", line 177, in __init__
    deterministic=self.deterministic
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/models/model.py", line 550, in create_output_operations
    reward=reward
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 278, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/home/lefnire/anaconda3/envs/btc3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/models/q_model.py", line 91, in tf_loss_per_instance
    q_value = self.tf_q_value(embedding=embedding, distr_params=distr_params, action=actions[name][:-1], name=name)
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/models/q_model.py", line 64, in tf_q_value
    return self.distributions[name].state_action_value(distr_params=distr_params, action=action)
AttributeError: 'Beta' object has no attribute 'state_action_value'

originally defined at:
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/models/model.py", line 147, in __init__
    self.initialize(custom_getter=custom_getter)
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/models/q_model.py", line 56, in initialize
    super(QModel, self).initialize(custom_getter)
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/models/distribution_model.py", line 102, in initialize
    super(DistributionModel, self).initialize(custom_getter)
  File "/home/lefnire/Sites/btc/tmp/tensorforce2/tensorforce/models/model.py", line 319, in initialize
    custom_getter_=custom_getter

```

**Comment by lefnire** [comment]
Something else at play here, likely on my end. Will re-open otherwise.

**Comment by AlexKuhnle** [comment]
Hey @lefnire, this is actually a more experimental feature that is currently not supported for the Beta distribution (hence actions with min_value and/or max_value). we are planning to blog about it soon-ish, it's related to more recent papers about a kind of equivalence between policy gradient and q-models, but for now best consider DQN only working with discrete actions -- unbounded continuous also 'work', but not (yet) a proper feature.

**Comment by lefnire** [comment]
Gotcha. Right, I had something wonky on my end - was trying to use DQN vanilla, didn't mean to mess with distributions

**Comment by AlexKuhnle** [comment]
Not exactly false alarm, just straight into uncovering some 'potentially' new features... ;-)  as you've maybe seen, q_model also inherits from distribution_model, so in fact *uses* a distribution, which is something we've not seen before, but it nevertheless seems to make sense and is along the lines of quite a few papers recently. but this is a part we want to discuss at some point soon... anyway, DQN with discrete actions should work as expected, but feel free to play around with continuous DQN if you're curious (and in that case let us know what you think).
