### ISSUE TITLE
exploration by NAF

### ISSUE THREAD

**Issue by aGiant** [reinforceio/tensorforce#192]
Hi, 
exploration configure for NAFAgent was：
	exploration = {
		"type": "OrnsteinUhlenbeckProcess",
        "sigma":0.1,
        "mu":0,
        "theta":0.1},
but got error:
Traceback (most recent call last):
  File "tensorforce_trading_naf_2.py", line 137, in <module>
    agent = NAFAgent(config=config_naf) # config_naf
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/memory_agent.py", line 62, in __init__
    super(MemoryAgent, self).__init__(config, model)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/agent.py", line 151, in __init__
    self.exploration[name] = Exploration.from_config(config=config.exploration[name])
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/explorations/exploration.py", line 29, in from_config
    predefined=tensorforce.core.explorations.explorations
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/util.py", line 170, in get_object
    obj = get_function(fct=fct, predefined=predefined)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/util.py", line 139, in get_function
    module_name, function_name = fct.rsplit('.', 1)
ValueError: need more than 1 value to unpack

**Comment by AlexKuhnle** [comment]
Hi @aGiant,

for predefined exploration methods (or preprocessing, optimizer, etc) we use special key values defined [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/explorations/__init__.py#L30), so in your case the `"type"` entry should be `"ornstein_uhlenbeck"` for it to work.

Reopen if not.

**Comment by aGiant** [comment]
Hi @AlexKuhnle ,
"type": "ornstein_uhlenbeck" works. The old setting came from https://reinforce.io/blog/introduction-to-tensorforce/. Maybe you can correct it too.
Thanks

**Comment by AlexKuhnle** [comment]
Oh yes, thanks for pointing out.
