### ISSUE TITLE
updated to 0.3.2 NAFAgent still does not work

### ISSUE THREAD

**Issue by aGiant** [reinforceio/tensorforce#236]
Hi NAF still does not work.

Configure:

config_naf = Configuration(
    batch_size=batch_size, #update_frequency = 96, #epochs=10,
	learning_rate=0.008,
	discount = gold_rate, #0.99, #distributed = True,
	normalize_rewards=True, use_target_network=True,
	#memory='prioritized_replay', #min_replay_size=240,
	#first_update=10000, #repeat_update=960,
    #memory_capacity=3000000,#normalize_rewards=True,
	#target_update_frequency = 48,
	#update_target_weight = 0.5,
	#keep_last = False,
	#optimizer = 'adam',
	#clip_loss = 0.2,
	#baseline = 'linear',
	#gae_rewards = True, gae_lambda = 0.9,
	baseline =  {
    "type": "mlp",#"linear", #
    "sizes": [1280, 640, 320] ,#, 160 80, 40],
    "epochs": 1,
    "update_batch_size" : batch_size,
    "learning_rate": 0.01
  	},
	exploration = {
		"type": "ornstein_uhlenbeck",
        "sigma":0.1,
        "mu":0,
        "theta":0.1}
	#,
	#optimizer = {
    #"type": "rmsprop",
    #"momentum": 0.9,
    #"epsilon": 0.01
  	#}#sigmoid
)

Errors:

Traceback (most recent call last):
  File "/home/llu/Data/tensorforce_trading_naf_2.py", line 165, in <module>
    agent = NAFAgent(states_spec=states, actions_spec=actions, network_spec=network, config=config) # config_naf
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/naf_agent.py", line 111, in __init__
    super(NAFAgent, self).__init__(states_spec, actions_spec, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/memory_agent.py", line 51, in __init__
    super(MemoryAgent, self).__init__(states_spec, actions_spec, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/agent.py", line 177, in __init__
    config=config
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/agents/naf_agent.py", line 118, in initialize_model
    config=config
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/q_naf_model.py", line 47, in __init__
    config=config
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/q_model.py", line 54, in __init__
    config=config
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/distribution_model.py", line 98, in __init__
    config=config
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 181, in __init__
    deterministic=self.deterministic
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 592, in create_output_operations
    reward=reward
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 261, in __call__
    return self._call_func(args, kwargs, check_for_new_variables=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/q_model.py", line 128, in tf_optimization
    optimization = super(QModel, self).tf_optimization(states, internals, actions, terminal, reward)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 516, in tf_optimization
    return self.optimizer.minimize(**optimizer_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/optimizer.py", line 81, in minimize
    deltas = self.step(time=time, variables=variables, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 261, in __call__
    return self._call_func(args, kwargs, check_for_new_variables=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/tf_optimizer.py", line 82, in tf_step
    applied = self.optimizer.minimize(loss=loss, var_list=variables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 325, in minimize
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 446, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/adam.py", line 132, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 766, in _zeros_slot
    named_slots[_var_key(var)] = slot_creator.create_zeros_slot(var, op_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 146, in create_slot_with_initializer
    dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 360, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 140, in custom_getter
    variable = getter(name=name, **kwargs)  # Top-level, hence no 'registered'
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 682, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable optimization/step/optimization/step/loss/loss-per-instance/apply_2/W/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

originally defined at:
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 172, in __init__
    self.optimizer = Optimizer.from_spec(spec=config.optimizer)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/optimizer.py", line 102, in from_spec
    kwargs=kwargs
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/util.py", line 167, in get_object
    return obj(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/tf_optimizer.py", line 45, in wrapper
    return TFOptimizer(optimizer=optimizer, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/tf_optimizer.py", line 57, in __init__
    super(TFOptimizer, self).__init__()
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/core/optimizers/optimizer.py", line 50, in __init__
    custom_getter=custom_getter

originally defined at:
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 151, in __init__
    self.initialize(custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/distribution_model.py", line 102, in initialize
    super(DistributionModel, self).initialize(custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorforce/models/model.py", line 336, in initialize
    custom_getter_=custom_getter

**Comment by michaelschaarschmidt** [comment]
NAF cannot use a baseline

**Comment by michaelschaarschmidt** [comment]
In any case there is no good reason to use NAF, it is likely strictly inferior to PPO

**Comment by aGiant** [comment]
baseline and exploration both are out. But it still does not work.

**Comment by michaelschaarschmidt** [comment]
Please check the NAF test. Actually I am just seeing that you are using a Configuration object, which is not used in the latest API any more. I would recommend copying the basic test configuration and then expand parameters from there, and also ensure tensorflow > 1.3

**Comment by AlexKuhnle** [comment]
In addition to updating TensorFlow and TensorForce, another thing worth trying is running it with Python3, as we recently sometimes found Python2 causing weird problems in certain combinations within TensorFlow. Python2 should ideally work, of course, but it's good to know if it's related to this issue.

**Comment by aGiant** [comment]
Same configure PPOAgent works but NAFAgent does not. NAF is the only algo that works in our case.

**Comment by michaelschaarschmidt** [comment]
The test is starting so this is very likely a problem with your configuration. Nonetheless NAF might be buggy due to the change to distribution model.

**Comment by michaelschaarschmidt** [comment]
NAF test is now passing with latest master locally for me, there was indeed a bug.
