### ISSUE TITLE
TypeError: conv1d() got an unexpected keyword argument 'input'

### ISSUE THREAD

**Issue by amitrack** [reinforceio/tensorforce#254]
#Hello there,
I'm new to RL and have been trying to use tensorforce on some time series data but I keep recieving the same error.
Here's my code 
```
agent= DQNAgent(
    states_spec=dict(type="float",shape=(256,8)),
    actions_spec=dict(type='int', num_actions=3),
    network_spec=[
        {
            "type": "conv1d",
            "size": 32,
        },
        {
            "type": "conv1d",
            "size": 64,
        },
        {
            "type": "flatten"
        },
        {
            "type": "dense",
            "size": 512
        }
    

 ])


```
And here is the error I've been getting:

```
Traceback (most recent call last):
  File "C:/Users/XXX/Workspace/src/train.py", line 28, in <module>
    "size": 512
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\agents\dqn_agent.py", line 218, in __init__
    repeat_update=repeat_update
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\agents\memory_agent.py", line 60, in __init__
    batched_observe=batched_observe
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\agents\agent.py", line 174, in __init__
    actions_spec=self.actions_spec,
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\agents\dqn_agent.py", line 242, in initialize_model
    random_sampling_fix=True
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\q_model.py", line 82, in __init__
    entropy_regularization=entropy_regularization,
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\distribution_model.py", line 69, in __init__
    variable_noise=variable_noise
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\model.py", line 113, in __init__
    self.setup()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\model.py", line 227, in setup
    deterministic=self.deterministic_input
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\model.py", line 736, in create_output_operations
    deterministic=deterministic
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 278, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\distribution_model.py", line 140, in tf_actions_and_internals
    embedding, internals = self.network.apply(x=states, internals=internals, update=update, return_internals=True)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 278, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\core\networks\network.py", line 241, in tf_apply
    x = layer.apply(x, update, *layer_internals)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 278, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\core\networks\layer.py", line 600, in tf_apply
    x = tf.nn.conv1d(input=x, filter=self.filters, strides=self.stride, padding=self.padding)
TypeError: conv1d() got an unexpected keyword argument 'input'

originally defined at:
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\model.py", line 194, in setup
    self.initialize(custom_getter=custom_getter)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\q_model.py", line 86, in initialize
    super(QModel, self).initialize(custom_getter)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\distribution_model.py", line 78, in initialize
    kwargs=dict(summary_labels=self.summary_labels)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\core\networks\network.py", line 135, in from_spec
    kwargs=kwargs
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\util.py", line 172, in get_object
    return obj(*args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\core\networks\network.py", line 226, in __init__
    kwargs=dict(scope=scope, summary_labels=summary_labels)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\core\networks\layer.py", line 137, in from_spec
    kwargs=kwargs
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\util.py", line 172, in get_object
    return obj(*args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\core\networks\layer.py", line 590, in __init__
    super(Conv1d, self).__init__(scope=scope, summary_labels=summary_labels)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\core\networks\layer.py", line 60, in __init__
    custom_getter_=custom_getter


originally defined at:
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\model.py", line 194, in setup
    self.initialize(custom_getter=custom_getter)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\q_model.py", line 86, in initialize
    super(QModel, self).initialize(custom_getter)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\distribution_model.py", line 78, in initialize
    kwargs=dict(summary_labels=self.summary_labels)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\core\networks\network.py", line 135, in from_spec
    kwargs=kwargs
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\util.py", line 172, in get_object
    return obj(*args, **kwargs)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\core\networks\network.py", line 212, in __init__
    super(LayeredNetwork, self).__init__(scope=scope, summary_labels=summary_labels)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\core\networks\network.py", line 147, in __init__
    super(LayerBasedNetwork, self).__init__(scope=scope, summary_labels=summary_labels)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\core\networks\network.py", line 56, in __init__
    custom_getter_=custom_getter


originally defined at:
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\model.py", line 194, in setup
    self.initialize(custom_getter=custom_getter)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\q_model.py", line 86, in initialize
    super(QModel, self).initialize(custom_getter)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\distribution_model.py", line 73, in initialize
    super(DistributionModel, self).initialize(custom_getter)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorforce\models\model.py", line 500, in initialize
    custom_getter_=custom_getter


```

I would be grateful for any and all help

**Comment by michaelschaarschmidt** [comment]
That was an old TensorFlow API in 1d which has since been updated a few days ago, so your TensorForce version is not up to date:

https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/layer.py#L730
