### ISSUE TITLE
OSError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by cc3941329** [reinforceio/tensorforce#303]
i am trying to run the quickstart.py,however ,it shows this when i set env = OpenAIGym('CartPole-v0',visualize=True)
`Unexpected error loading library libGL.so.1: dlopen: cannot load any more object with static TLS
Traceback (most recent call last):
  File "/home/cc/tensorflow/test_tf.py", line 58, in <module>
    runner.run(episodes=3000, max_episode_timesteps=200, episode_finished=episode_finished)
  File "/home/cc/example_code/tensorforce/tensorforce/execution/runner.py", line 122, in run
    state, terminal, reward = self.environment.execute(actions=action)
  File "/home/cc/example_code/tensorforce/tensorforce/contrib/openai_gym.py", line 70, in execute
    self.gym.render()
  File "/home/cc/gym/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/cc/gym/gym/core.py", line 286, in _render
    return self.env.render(mode, close)
  File "/home/cc/gym/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/cc/gym/gym/envs/classic_control/cartpole.py", line 115, in _render
    from gym.envs.classic_control import rendering
  File "/home/cc/gym/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/home/cc/anaconda2/lib/python2.7/site-packages/pyglet/gl/__init__.py", line 97, in <module>
    from pyglet.gl.lib import GLException
  File "/home/cc/anaconda2/lib/python2.7/site-packages/pyglet/gl/lib.py", line 142, in <module>
    from pyglet.gl.lib_glx import link_GL, link_GLU, link_GLX
  File "/home/cc/anaconda2/lib/python2.7/site-packages/pyglet/gl/lib_glx.py", line 50, in <module>
    gl_lib = pyglet.lib.load_library('GL')
  File "/home/cc/anaconda2/lib/python2.7/site-packages/pyglet/lib.py", line 135, in load_library
    lib = ctypes.cdll.LoadLibrary(name)
  File "/home/cc/anaconda2/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/home/cc/anaconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen: cannot load any more object with static TLS`
but everything works fine whem i set `env = OpenAIGym('CartPole-v0',visualize=False)`
so how can i visualize while  i am training?
thanks

**Comment by michaelschaarschmidt** [comment]
Hello, this is a known a gym/library issue on your end, not a TensorForce issue:
https://github.com/tflearn/tflearn/issues/403
https://github.com/openai/gym/issues/396#issuecomment-257028923

"
Linux has a static limit on the number of shared libraries with TLS (Thread-Local Storage, to support C++'s __thread storage class) that can be loaded into a process. Gym itself doesn't use shared libraries, but OpenGL and Tensorflow both have several libraries. The limit is small, like 14 or 32 depending on OS version (it's the version of glibc that matters).
"

**Comment by cc3941329** [comment]
@michaelschaarschmidt thanks for your answer,but i have tried the mothods they mentioned,like change the order of importing libraries,however,it dosen't work.

**Comment by michaelschaarschmidt** [comment]
Have you updated TensorFlow and TensorForce and gym all to latest versions?

**Comment by cc3941329** [comment]
@michaelschaarschmidt  yes  i already update to the latest

**Comment by michaelschaarschmidt** [comment]
Sorry there is not much we can do here unless maybe changing operating system if possible on a virtual machine. I suggest creating an issue with openai gym, because it really is a gym issue rather than a tensorforce issue.

**Comment by cc3941329** [comment]
@michaelschaarschmidt  I updated the ubuntu from 14 to 16. and now everything seems to be ok. It seems is the system's limitation in ubuntu 14. thanks!
