### ISSUE TITLE
Setting Up DQN Agent

### ISSUE THREAD

**Issue by bching28** [reinforceio/tensorforce#325]
Hi,

I'm running into this AttributeError when attempting to set up the DQN Agent:

```
Traceback (most recent call last):
  File "choice.py", line 24, in <module>
    network_spec=dict(type='dense', size=64, activation='relu')
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/agents/dqn_agent.py", line 110, in __init__
    repeat_update=repeat_update
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/agents/memory_agent.py", line 94, in __init__
    entropy_regularization=entropy_regularization
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/agents/learning_agent.py", line 138, in __init__
    scope=scope
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/agents/agent.py", line 82, in __init__
    self.model = self.initialize_model()
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/agents/dqn_agent.py", line 137, in initialize_model
    random_sampling_fix=True
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/models/q_model.py", line 88, in __init__
    entropy_regularization=entropy_regularization,
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/models/distribution_model.py", line 76, in __init__
    reward_preprocessing_spec=reward_preprocessing_spec
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/models/model.py", line 238, in __init__
    self.setup()
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/models/model.py", line 338, in setup
    self.initialize(custom_getter=custom_getter)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/models/q_model.py", line 92, in initialize
    super(QModel, self).initialize(custom_getter)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/models/distribution_model.py", line 85, in initialize
    kwargs=dict(summary_labels=self.summary_labels)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/core/networks/network.py", line 154, in from_spec
    kwargs=kwargs
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/util.py", line 162, in get_object
    predef_obj_keys = list(predefined_objects.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

Now I understand that `predef_obj_keys` is set to `NONE` in the `get_object()` function definition in `util.py`.  But I can't determine where to alter the value of `predef_obj_keys` or what values to feed into `predef_obj_keys`.  It might be possible that my `network_spec` is not configured properly, but I am not entirely sure.

**Comment by AlexKuhnle** [comment]
The way `None` is handled here is wrong, but this is not what causes your problem. Could you post your agent specification/arguments, since otherwise it's hard to see what might cause the problem...

**Comment by bching28** [comment]
Sure. Here is my agent specifications:
``` python
d = {}
d['state1'] = dict(type='int', shape=()) # not sure why shape has to be empty
d['state2'] = dict(type='int', shape=())

agent = DQNAgent(
    states_spec = d,
    actions_spec = dict(type='int', num_actions=2),
    network_spec=dict(type='dense', size=64, activation='relu')
)
```

`state1` and `state2` are simply integer values that change during each step in an episode. And I currently only want two actions (True and False).

**Comment by AlexKuhnle** [comment]
Ah, I see... There are various comments here:
- The `shape` of a state defines the state array dimensions. So, for instance, you might consider using `shape=2` (short for `shape=(2,)`) instead of two single-value states.
- Are your states really `int`s? If so, there are things to be aware of (basically, it won't work quite like this), otherwise use `type='float'`.
- The `network_spec` has to be a list of layers, so `network_spec=[dict(type='dense', size=64, activation='relu')]` should solve your problem.
- There is an action type `bool`, which you might consider using if you want `True` and `False` as actions.

**Comment by bching28** [comment]
Could you elaborate on what you mean by your second bullet point? What did you mean by "it won't work quite like this"? Because yes, my states are `int`s.

**Comment by AlexKuhnle** [comment]
Yes: Dense layers (and almost all other layers) work with float tensors, and although integer inputs could implicitly converted to the corresponding floats (would have to be explicit in TensorFlow), this is often not ideal. Particularly if there is a range of possible inputs `a <= x <= b`, using an `embedding` layer ([here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/layer.py#L356)) before dense layers is probably best. If all integers are possible, converting them to float before passing them to TensorForce might be a good solution.

**Comment by bching28** [comment]
So based on your previous comments, would the following be a reasonable assumption to do? I typecasted the integer variables to float before storing them in a `dict()` and feeding the dict into `agent.act()`.

``` python
state=dict(type='float', shape=(2,))

agent = DQNAgent(
    states_spec = state,
    actions_spec = dict(type='int', num_actions=2),
    network_spec=[dict(type='dense', size=64, activation='relu')]
)
```

And then someone further down my code:
``` python
states_dict = {}
key = ["state1", "state2"]
value = [ float(state1), float(state2) ]
for i in range (len(key)):
    states_dict[key[i]] = value[i]

action = agent.act(states_dict)
```

When I change the `type` to `float` for the `states_spec`, I get this error:
```
2018-02-05 14:01:21.200376: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Traceback (most recent call last):
  File "choice.py", line 103, in <module>
    doSomething()
  File "choice.py", line 50, in doSomething
    if ( choice( float(curr_sum), float(rand_num) ) ): # choice function should return true or false
  File "choice.py", line 90, in choice
    action = agent.act(states_dict)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/agents/agent.py", line 145, in act
    deterministic=deterministic
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/models/model.py", line 1268, in act
    actions, internals, timestep = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1024, in run
    run_metadata=run_metadata)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 827, in run
    return self._sess.run(*args, **kwargs)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1089, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/bching/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number
```

**Comment by AlexKuhnle** [comment]
Yes, this looks good, apart from one small issue which, I assume, causes this exception: the state dict you pass to the agent now doesn't have two states, but only one, so: `state = [float(state1), float(state2)]`. As an aside: `dict(type=..., shape=...)` is a shortform for `dict(state=dict(type=..., shape=...))`, which has to be consistently used, hence the above state representation instead of `state = dict(state=[float(state1, float(state2)])`. Hope that works!

**Comment by bching28** [comment]
That did fix the problem. Thanks! I just had some follow up questions that popped into mind. 

- So instead of having two separate state values, I combined them to have a `shape=2`. When I read the documentation, my understanding was that each state component needed its own state definition. What are some examples of when I would have multiple state components?

- Based on your last comment, if I did have multiple state components, then would this be an appropriate way of representing them ("..." just means more inputs):
``` python
state=[dict(type='float', shape=(64,64)), dict(type='float', shape=(32,32)), ...]
```

- When looking for how to configure `network_spec`, I saw a couple implementations.  Sometimes the list had multiple dictionary inputs:
``` python
network_spec=[dict(type='dense', size=64, activation='relu'), dict(type='dense', size=64, activation='relu'), ...]
```
When would an agent need to have multiple inputs in its `network_spec` list?

- You also mentioned that there is a type `bool` for actions. What would be needed for its dictionary configuration? Would it be only the following:
``` python
actions_spec = dict(type='bool')
```

**Comment by AlexKuhnle** [comment]
- First and foremost, multiple states are necessary if you have different *types* of inputs, so `'int'` and `'float'` etc. But also more generally, if you want to have a network that handles different parts inputs differently (in a more complex network than a simple layered one), specifying multiple states makes sense.
- Not quite, the state specification is always a dict (with the option of a single-state short-form), so: `dict(state1=dict(...), state2=dict(...), ...)`.
- Multiple items in the `network_spec` list specify multiple layers of the network, so your example is a two-layer dense network. Other common network specifications are, for instance, `n x conv -> pooling -> k x dense` or so.
- Yes exactly, or optionally a `shape` argument, if you want an array of boolean actions.

I assume this issue can be tagged as 'closed' then... :-)
