### ISSUE TITLE
ImportError: cannot import name 'Queue'

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#329]
Latest merge into #memory (Feb 5th), looks like a Queue class was removed but still trying to import:

```shell
/home/lefnire/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "hypersearch.py", line 29, in <module>
    from tensorforce.agents import agents as agents_dict
  File "/home/lefnire/tensorforce/tensorforce/agents/__init__.py", line 17, in <module>
    from tensorforce.agents.constant_agent import ConstantAgent
  File "/home/lefnire/tensorforce/tensorforce/agents/constant_agent.py", line 27, in <module>
    from tensorforce.models.constant_model import ConstantModel
  File "/home/lefnire/tensorforce/tensorforce/models/__init__.py", line 17, in <module>
    from tensorforce.models.memory_model import MemoryModel
  File "/home/lefnire/tensorforce/tensorforce/models/memory_model.py", line 23, in <module>
    from tensorforce.core.memories import Memory
  File "/home/lefnire/tensorforce/tensorforce/core/memories/__init__.py", line 18, in <module>
    from tensorforce.core.memories.prioritized_replay import PrioritizedReplay
  File "/home/lefnire/tensorforce/tensorforce/core/memories/prioritized_replay.py", line 22, in <module>
    from tensorforce.core.memories import Queue
ImportError: cannot import name 'Queue'
```

**Comment by michaelschaarschmidt** [comment]
How do you mean, removed? 
https://github.com/reinforceio/tensorforce/blob/memory/tensorforce/core/memories/queue.py

Might be an error with import order in the init, pushed a potential fix if you could try again

**Comment by lefnire** [comment]
@michaelschaarschmidt that fixed it!

**Comment by michaelschaarschmidt** [comment]
ok great
