### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Must have updates.shape = indices.shape + params.shape[1:], got updates.shape [352], indices.shape [254], params.shape [100000]

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#335]
Rebased #memory today starting at c2c9dddf6d99bfa14b8ffb65b507a6be50b0ad6e. I'm using PPO, `memory = {'type': 'latest', 'include_next_states': False, 'capacity': 100000}`. I'm using both multi-state and multi-action, they're both dicts (though I'd mention seeing `initialize/action-action` in the error).

LMK if nothing obvious pops up and I'll try to replicate w/ one in the examples dir.

```shell
Traceback (most recent call last):
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Must have updates.shape = indices.shape + params.shape[1:], got updates.shape [352], indices.shape [254], params.shape [100000]
         [[Node: ppo/observe-timestep/store/ScatterUpdate_2 = ScatterUpdate[T=DT_INT32, Tindices=DT_INT32, _class=["loc:@ppo/initialize/latest/initialize/action-action"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/initialize/latest/initialize/action-action, ppo/observe-timestep/store/mod/_347, ppo/StopGradient_2, ^ppo/observe
-timestep/store/AssignSub)]]
         [[Node: ppo/observe-timestep/store/ScatterUpdate_2/_384 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_147_ppo/observe-timestep/store/ScatterUpdate_2", tensor_type=DT_FLOAT, _device="/job:localhost/repl
ica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hypersearch.py", line 809, in <module>
    main()
  File "hypersearch.py", line 805, in main
    y_list=Y
  File "/home/lefnire/btcbot/gp.py", line 218, in bayesian_optimisation2
    loss_fn(next_sample)
  File "hypersearch.py", line 756, in loss_fn
    reward = hsearch.execute(vec2hypers(params))
  File "hypersearch.py", line 582, in execute
    env.train_and_test(agent, self.cli_args.n_steps, self.cli_args.n_tests, -1)
  File "/home/lefnire/btcbot/btc_env.py", line 514, in train_and_test
    runner.run(timesteps=timesteps_each)
  File "/home/lefnire/tensorforce/tensorforce/execution/runner.py", line 131, in run
    self.agent.observe(terminal=terminal, reward=reward)
  File "/home/lefnire/tensorforce/tensorforce/agents/agent.py", line 216, in observe
    reward=self.observe_reward
  File "/home/lefnire/tensorforce/tensorforce/models/model.py", line 1188, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 539, in run
    run_metadata=run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1104, in run
    raise six.reraise(*original_exc_info)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1089, in run
    return self._sess.run(*args, **kwargs)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1161, in run
    run_metadata=run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 941, in run
    return self._sess.run(*args, **kwargs)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Must have updates.shape = indices.shape + params.shape[1:], got updates.shape [352], indices.shape [254], params.shape [100000]
         [[Node: ppo/observe-timestep/store/ScatterUpdate_2 = ScatterUpdate[T=DT_INT32, Tindices=DT_INT32, _class=["loc:@ppo/initialize/latest/initialize/action-action"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/initialize/latest/initialize/action-action, ppo/observe-timestep/store/mod/_347, ppo/StopGradient_2, ^ppo/observe
-timestep/store/AssignSub)]]
         [[Node: ppo/observe-timestep/store/ScatterUpdate_2/_384 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_147_ppo/observe-timestep/store/ScatterUpdate_2", tensor_type=DT_FLOAT, _device="/job:localhost/repl
ica:0/task:0/device:GPU:0"]()]]

Caused by op 'ppo/observe-timestep/store/ScatterUpdate_2', defined at:
  File "hypersearch.py", line 809, in <module>
    main()
  File "hypersearch.py", line 805, in main
    y_list=Y
  File "/home/lefnire/btcbot/gp.py", line 218, in bayesian_optimisation2
    loss_fn(next_sample)
  File "hypersearch.py", line 756, in loss_fn
    reward = hsearch.execute(vec2hypers(params))
  File "hypersearch.py", line 579, in execute
    **hydrated
  File "/home/lefnire/tensorforce/tensorforce/agents/ppo_agent.py", line 176, in __init__
    entropy_regularization=entropy_regularization
  File "/home/lefnire/tensorforce/tensorforce/agents/learning_agent.py", line 132, in __init__
    batching_capacity=batching_capacity
  File "/home/lefnire/tensorforce/tensorforce/agents/agent.py", line 85, in __init__
    self.model = self.initialize_model()
  File "/home/lefnire/tensorforce/tensorforce/agents/ppo_agent.py", line 204, in initialize_model
  File "/home/lefnire/tensorforce/tensorforce/agents/ppo_agent.py", line 204, in initialize_model
    likelihood_ratio_clipping=self.likelihood_ratio_clipping
  File "/home/lefnire/tensorforce/tensorforce/models/pg_prob_ratio_model.py", line 88, in __init__
    gae_lambda=gae_lambda
  File "/home/lefnire/tensorforce/tensorforce/models/pg_model.py", line 95, in __init__
    requires_deterministic=False
  File "/home/lefnire/tensorforce/tensorforce/models/distribution_model.py", line 86, in __init__
    discount=discount
  File "/home/lefnire/tensorforce/tensorforce/models/memory_model.py", line 80, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/lefnire/tensorforce/tensorforce/models/model.py", line 214, in __init__
    self.setup()
  File "/home/lefnire/tensorforce/tensorforce/models/model.py", line 355, in setup
    deterministic=deterministic
  File "/home/lefnire/tensorforce/tensorforce/models/memory_model.py", line 548, in create_operations
    deterministic=deterministic
  File "/home/lefnire/tensorforce/tensorforce/models/model.py", line 998, in create_operations
    self.create_observe_operations(reward=reward, terminal=terminal)
  File "/home/lefnire/tensorforce/tensorforce/models/model.py", line 980, in create_observe_operations
    reward=reward
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 283, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 222, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/lefnire/tensorforce/tensorforce/models/memory_model.py", line 452, in tf_observe_timestep
    reward=reward
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 266, in __call__
    return self._call_func(args, kwargs, check_for_new_variables=True)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 222, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/lefnire/tensorforce/tensorforce/core/memories/queue.py", line 175, in tf_store
    updates=action
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 349, in scatter_update
    use_locking=use_locking, name=name)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 920, in scatter_update
    use_locking=use_locking, name=name)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Must have updates.shape = indices.shape + params.shape[1:], got updates.shape [352], indices.shape [254], params.shape [100000]
         [[Node: ppo/observe-timestep/store/ScatterUpdate_2 = ScatterUpdate[T=DT_INT32, Tindices=DT_INT32, _class=["loc:@ppo/initialize/latest/initialize/action-action"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/initialize/latest/initialize/action-action, ppo/observe-timestep/store/mod/_347, ppo/StopGradient_2, ^ppo/observe
-timestep/store/AssignSub)]]
         [[Node: ppo/observe-timestep/store/ScatterUpdate_2/_384 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_147_ppo/observe-timestep/store/ScatterUpdate_2", tensor_type=DT_FLOAT, _device="/job:localhost/repl
ica:0/task:0/device:GPU:0"]()]]
```

**Comment by lefnire** [comment]
Looks like it's memory related. I've fixed `memory.capacity` to the exact `batch_size * episode_len` (and fixing `episode_len` so it won't terminate early, so `episode_len` is always reached) and the problem goes away. Possibly an issue when `memory.capacity` doesn't fill up all the way?

**Comment by AlexKuhnle** [comment]
That sounds unexpected indeed, so if you can provide an example to reproduce the message, that would be helpful. I encountered this problem in distributed mode in the last days, but in the end all tests and distributed seemed to work, and we seem to cover multi-state/action PPO. It's interesting, though, that the problem seems to happen for actions, not for states/internals (which are assigned before).

**Comment by dustinul6** [comment]
Hi guys, thanks very much for the great project. 
However, I ran into the same problem when I pulled the master today. I'm running a custom environment with single action and state. The training used to work before the memory branch is merged. I cannot reproduce it with OpenAI gym examples yet. 
Here are the configurations.
`environment.actions = {'num_actions': 8, 'type': 'int'}`
`environment.states={'shape': (16,), 'type': 'float'}`
Memory capacity is 5000. Update batch_size is 100. (I tried different combinations of these 2 numbers, the error still occurs.) Single-thread runner on CPU.
It is not feasible to fix the episode length in my environment, so the workaround @lefnire mentioned doesn't work for me.
Please let me know if you need more information. Any hint of fixes or workarounds will be very much appreciated. Thanks!! 

---
`Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Must have updates.shape = indices.shape + params.shape[1:], got updates.shape [23,16], indices.shape [2], params.shape [5000,16]
         [[Node: ppo/observe-timestep/store/ScatterUpdate = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@ppo/initialize/latest/initialize/state-state"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/initialize/latest/initialize/state-state, ppo/observe-timestep/store/mod, ppo/strided_slice_3, ^ppo/observe-timestep/store/AssignSub)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 39, in <module>
    main()
  File "train.py", line 36, in main
    experiment.train(run_spec)
  File "/home/ubuntu/projects/multiopt/experiment.py", line 209, in train
    max_episode_timesteps=50
  File "/home/ubuntu/projects/multiopt/train/my_runner.py", line 181, in run
    self.agent.observe(terminal=terminal, reward=reward)
  File "/home/ubuntu/projects/tensorforce/tensorforce/agents/agent.py", line 221, in observe
    reward=self.observe_reward
  File "/home/ubuntu/projects/tensorforce/tensorforce/models/model.py", line 1201, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1024, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 827, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Must have updates.shape = indices.shape + params.shape[1:], got updates.shape [23,16], indices.shape [2], params.shape [5000,16]
         [[Node: ppo/observe-timestep/store/ScatterUpdate = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@ppo/initialize/latest/initialize/state-state"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/initialize/latest/initialize/state-state, ppo/observe-timestep/store/mod, ppo/strided_slice_3, ^ppo/observe-timestep/store/AssignSub)]]

Caused by op 'ppo/observe-timestep/store/ScatterUpdate', defined at:
  File "train.py", line 39, in <module>
    main()
  File "train.py", line 36, in main
    experiment.train(run_spec)
  File "/home/ubuntu/projects/multiopt/experiment.py", line 146, in train
    self.restore_agent()
  File "/home/ubuntu/projects/multiopt/experiment.py", line 72, in restore_agent
    network=record["network_spec"]
  File "/home/ubuntu/projects/tensorforce/tensorforce/agents/agent.py", line 286, in from_spec
    kwargs=kwargs
  File "/home/ubuntu/projects/tensorforce/tensorforce/util.py", line 159, in get_object
    return obj(*args, **kwargs)
  File "/home/ubuntu/projects/tensorforce/tensorforce/agents/ppo_agent.py", line 151, in __init__
    entropy_regularization=entropy_regularization
  File "/home/ubuntu/projects/tensorforce/tensorforce/agents/learning_agent.py", line 149, in __init__
    batching_capacity=batching_capacity
  File "/home/ubuntu/projects/tensorforce/tensorforce/agents/agent.py", line 79, in __init__
    self.model = self.initialize_model()
  File "/home/ubuntu/projects/tensorforce/tensorforce/agents/ppo_agent.py", line 179, in initialize_model
    likelihood_ratio_clipping=self.likelihood_ratio_clipping
  File "/home/ubuntu/projects/tensorforce/tensorforce/models/pg_prob_ratio_model.py", line 88, in __init__
    gae_lambda=gae_lambda
  File "/home/ubuntu/projects/tensorforce/tensorforce/models/pg_model.py", line 95, in __init__
    requires_deterministic=False
  File "/home/ubuntu/projects/tensorforce/tensorforce/models/distribution_model.py", line 86, in __init__
    discount=discount
  File "/home/ubuntu/projects/tensorforce/tensorforce/models/memory_model.py", line 106, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/ubuntu/projects/tensorforce/tensorforce/models/model.py", line 199, in __init__
    self.setup()
  File "/home/ubuntu/projects/tensorforce/tensorforce/models/model.py", line 340, in setup
    deterministic=deterministic
  File "/home/ubuntu/projects/tensorforce/tensorforce/models/memory_model.py", line 572, in create_operations
    deterministic=deterministic
  File "/home/ubuntu/projects/tensorforce/tensorforce/models/model.py", line 984, in create_operations
    self.create_observe_operations(reward=reward, terminal=terminal)
  File "/home/ubuntu/projects/tensorforce/tensorforce/models/model.py", line 966, in create_observe_operations
    reward=reward
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 278, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/ubuntu/projects/tensorforce/tensorforce/models/memory_model.py", line 481, in tf_observe_timestep
    reward=reward
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 261, in __call__
    return self._call_func(args, kwargs, check_for_new_variables=True)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/ubuntu/projects/tensorforce/tensorforce/core/memories/queue.py", line 169, in tf_store
    updates=state
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 786, in scatter_update
    use_locking=use_locking, name=name)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Must have updates.shape = indices.shape + params.shape[1:], got updates.shape [23,16], indices.shape [2], params.shape [5000,16]
         [[Node: ppo/observe-timestep/store/ScatterUpdate = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@ppo/initialize/latest/initialize/state-state"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/initialize/latest/initialize/state-state, ppo/observe-timestep/store/mod, ppo/strided_slice_3, ^ppo/observe-timestep/store/AssignSub)]]
`

**Comment by michaelschaarschmidt** [comment]
So in core/memories/queue

```
                assignments.append(tf.scatter_update(
                    ref=self.states_memory[name],
                    indices=indices,
                    updates=state
                ))
```

fails because of the shape of indices versus the shape of updates if I see correctly.

The only way this can happen I can see is if:

```
        num_instances = tf.shape(input=terminal)[0]
        indices = tf.range(start=self.memory_index, limit=(self.memory_index + num_instances)) % self.capacity
```

Produces the wrong number of instances from the shape of terminal vs the shape of states. I haven't been able to reproduce this but just to make sure it's not something so simple, can you change 

```
  num_instances = tf.shape(input=terminal)[0]
```

to 

```
  num_instances = tf.shape(input=states)[0]
```
(or reward)?

**Comment by AlexKuhnle** [comment]
Hey @lefnire and @dustinul6,

After looking at potential sources for the problem, we identified that the reason might be that you call `act()` more often than `observe()` -- which indeed at some point was supposed to be possible, but with the latest update causes problems. The latest commit introduced an `independent` flag for `Agent.act()`, which should be used for independent action retrieval without a corresponding observation. If that is the case, let us know if this fix helps!

**Comment by AlexKuhnle** [comment]
(Side note: The two flags `independent` and `deterministic` kind of mean the same thing, it seems, so we might combine them at some point...)

**Comment by lefnire** [comment]
Ah! Indeed I'm doing that train/test bit, which calls act manually. Thanks for the note, I'll update when I can and report back.

**Comment by dustinul6** [comment]
Yes! Adding the independent flag did solve the problem! Now the runner runs smoothly. Thank you very much!

**Comment by mrbeann** [comment]
I think I get a similar error, but I make `observation` exactly the same as `act`.  The detail is 

```
PPOAgent(
            states= dict(type='float', shape=(6,)),
            
            actions = dict(
               a_action=dict(type='int', num_actions=3),
               b_action=dict(type='int', num_actions=2),
            ),
            
            network=[
                dict(type='dense', size=32, activation='relu'),
                dict(type='dense', size=32, activation='relu'),
            ],
```

And I call it with
```
agent.observe(reward=decision_reward, terminal=False) 
agent.act(state)
```

This result the following error:
InvalidArgumentError (see above for traceback): Must have updates.shape = indices.shape + params.shape[1:] or updates.shape = [], got updates.shape [999], indices.shape [1000], params.shape [10000]


Anyone can help with it?

**Comment by AlexKuhnle** [comment]
Is this with the newest version (ideally Github)?

**Comment by mrbeann** [comment]
> Is this with the newest version (ideally Github)?

yes, I tried 0.43 and compile it myself.

**Comment by AlexKuhnle** [comment]
Ah, cool, makes sense then, because the bug here should have been fixed. Probably include warnings soon to prevent incomprehensible error messages when something simple like this happens.
