### ISSUE TITLE
Maze Explorer in mode 0 TensorForceError: Invalid input rank for linear layer: 3, must be 2.

### ISSUE THREAD

**Issue by mkempers** [reinforceio/tensorforce#337]
When running the maze explorer example with the following configuration:
```
python examples/maze_explorer.py -a examples/configs/ppo.json -n examples/configs/mlp2_network.json --mode 0 --hide
```
The following error is thrown
```
Traceback (most recent call last):
  File "examples/maze_explorer.py", line 127, in <module>
    main()
  File "examples/maze_explorer.py", line 76, in main
    network_spec=network_spec
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/agents/agent.py", line 239, in from_spec
    kwargs=kwargs
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/util.py", line 173, in get_object
    return obj(*args, **kwargs)
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/agents/ppo_agent.py", line 125, in __init__
    keep_last_timestep=keep_last_timestep
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/agents/batch_agent.py", line 80, in __init__
    entropy_regularization=entropy_regularization
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/agents/learning_agent.py", line 138, in __init__
    scope=scope
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/agents/agent.py", line 82, in __init__
    self.model = self.initialize_model()
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/agents/ppo_agent.py", line 151, in initialize_model
    likelihood_ratio_clipping=self.likelihood_ratio_clipping
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/models/pg_prob_ratio_model.py", line 81, in __init__
    gae_lambda=gae_lambda,
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/models/pg_model.py", line 86, in __init__
    entropy_regularization=entropy_regularization,
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/models/distribution_model.py", line 76, in __init__
    reward_preprocessing_spec=reward_preprocessing_spec
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/models/model.py", line 238, in __init__
    self.setup()
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/models/model.py", line 376, in setup
    deterministic=self.deterministic_input
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/models/model.py", line 1109, in create_output_operations
    deterministic=deterministic
  File "/Users/marcelkempers/anaconda3/envs/py27ai/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 283, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/Users/marcelkempers/anaconda3/envs/py27ai/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 222, in _call_func
    result = self._func(*args, **kwargs)
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/models/distribution_model.py", line 145, in tf_actions_and_internals
    embedding, internals = self.network.apply(x=states, internals=internals, update=update, return_internals=True)
  File "/Users/marcelkempers/anaconda3/envs/py27ai/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 283, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/Users/marcelkempers/anaconda3/envs/py27ai/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 222, in _call_func
    result = self._func(*args, **kwargs)
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/core/networks/network.py", line 261, in tf_apply
    x = layer.apply(x, update, *layer_internals)
  File "/Users/marcelkempers/anaconda3/envs/py27ai/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 283, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/Users/marcelkempers/anaconda3/envs/py27ai/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 222, in _call_func
    result = self._func(*args, **kwargs)
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/core/networks/layer.py", line 628, in tf_apply
    xl1 = self.linear.apply(x=x, update=update)
  File "/Users/marcelkempers/anaconda3/envs/py27ai/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 283, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/Users/marcelkempers/anaconda3/envs/py27ai/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 222, in _call_func
    result = self._func(*args, **kwargs)
  File "/Users/marcelkempers/GIT/tensorforce/tensorforce/core/networks/layer.py", line 450, in tf_apply
    'Invalid input rank for linear layer: {}, must be 2.'.format(util.rank(x))
tensorforce.exception.TensorForceError: Invalid input rank for linear layer: 3, must be 2.
```
I suspected the error was caused by the shape of the observation space, (9,3). Therefore I tried to resolve the error by adding a flatten layer to the network, see branch flattenpreprocess in [my fork](https://github.com/mkempers/tensorforce.git). Unfortunately the error is still there. It is thrown at different moment though. I think during reward calculation. Now I have added a flatten option in the state preprocessing. This solves the issue. However, I am not sure this how the framework is intended to be used. Did I found a bug or introduced a new feature (flatten preprocessing)?

**Comment by Mazecreator** [comment]
I am not certain on the intent of the framework, but I believe what you have done is correct.  I don't think Linear supports a 2D (batch + 2 Dims) input structure.  I am not familiar with the example dataset and really don't have any more advice other than what you have done.  @AlexKuhnle might be able to speak to the Linear layer.  I don't know who introduced this code/data example.

**Comment by AlexKuhnle** [comment]
A flatten preprocessor sounds like the best solution here. This should also work without adding the flatten layer as part of the network. The preprocessor should also implement `processed_shape`. I would also change the code to the more basic `return tf.reshape(tensor=x, shape=(-1, util.prod(util.shape(x)[1:])))` (but doesn't really matter). A PR including these changes would be very welcome. :-)

**Comment by mkempers** [comment]
I wil start working on the PR :-)

**Comment by AndreasMegatranus** [comment]
Note that this error does not happen in mode 1.
