### ISSUE TITLE
Error in master branch: The node 'Merge/MergeSummary' has inputs from different frames.

### ISSUE THREAD

**Issue by yellowbee686** [reinforceio/tensorforce#350]
I've updated TensorForce to latest version, and if I add summarizer config like:
"summarizer": {
    "directory" : "./ppo",
    "labels": ["inputs", "losses", "variables", "activations"],
    "steps": 200
  }

 an error occurs:

Traceback (most recent call last):
  File "D:/TensorDemoCode/gym_test/cartpole/cartpole.py", line 38, in <module>
    runner.run(episodes=10000, max_episode_timesteps=200, episode_finished=episode_finished)
  File "d:\tensorforce\tensorforce\execution\runner.py", line 112, in run
    self.agent.observe(terminal=terminal, reward=reward)
  File "d:\tensorforce\tensorforce\agents\agent.py", line 221, in observe
    reward=self.observe_reward
  File "d:\tensorforce\tensorforce\models\model.py", line 1201, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "D:\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "D:\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "D:\Python36\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "D:\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1024, in run
    run_metadata=run_metadata)
  File "D:\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 827, in run
    return self._sess.run(*args, **kwargs)
  File "D:\Python36\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "D:\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "D:\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'Merge/MergeSummary' has inputs from different frames. The input 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/total-loss' is in frame 'ppo/observe-timestep/cond/optimization/multi-step/step/while/while_context'. The input 'ppo/ppo/inputs/rewards' is in frame ''.

**Comment by AlexKuhnle** [comment]
The summarizer is unfortunately generally broken in the current version. We hope to fix that very soon.

**Comment by r-lipton** [comment]
I am having also the problem when trying to get the histogram of actions
```
InvalidArgumentError: You must feed a value for placeholder tensor 'ppo/action-action' with dtype int32 and shape [?]
	 [[Node: ppo/action-action = Placeholder[dtype=DT_INT32, shape=[?], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: ppo/global-timestep/cond/pred_id/_679 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5945_ppo/global-timestep/cond/pred_id", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

While waiting for the fix, is there a way to print it?

**Comment by r-lipton** [comment]
Any news @AlexKuhnle @yellowbee686  ? 
Thanks

**Comment by michaelschaarschmidt** [comment]
No news - feel free to contribute on that end

**Comment by yellowbee686** [comment]
@r-lipton now you have to set summarizer to null

**Comment by AlexKuhnle** [comment]
The summarizers should work again with one of the latest commits, and the code now uses the new `tf.contrib.summary` framework. It's now relatively easy to add own summarizers in the code, just decide for a tag to be added to `summary_labels` and add the corresponding `tf.contrib.summary` command, as is done, for instance, [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/memory_model.py#L423):
```
if 'losses' in self.summary_labels or 'total-loss' in self.summary_labels:
    tf.contrib.summary.scalar(name='total-loss', tensor=loss)
```
