### ISSUE TITLE
 TypeError: init() got an unexpected keyword argument 'cell_clip'

### ISSUE THREAD

**Issue by Hir0fumi** [reinforceio/tensorforce#360]
It shows error while trying "python run.py --name test".(run.py is other repository file 'lefnire/tforce_btc_trader.git')
 What could be the cause of this (issue/problem)?
 Appreciate your help.

Traceback (most recent call last):
 File "run.py", line 57, in 
 main()
 File "run.py", line 43, in main
 **hydrated
 File "c:\users\administrator\rl\tensorforce\tensorforce\agents\ppo_agent.py", line 151, in init
 entropy_regularization=entropy_regularization
 File "c:\users\administrator\rl\tensorforce\tensorforce\agents\learning_agent.py", line 149, in init
 batching_capacity=batching_capacity
 File "c:\users\administrator\rl\tensorforce\tensorforce\agents\agent.py", line 79, in init
 self.model = self.initialize_model()
 File "c:\users\administrator\rl\tensorforce\tensorforce\agents\ppo_agent.py", line 179, in initialize_model
 likelihood_ratio_clipping=self.likelihood_ratio_clipping
 File "c:\users\administrator\rl\tensorforce\tensorforce\models\pg_prob_ratio_model.py", line 88, in init
 gae_lambda=gae_lambda
 File "c:\users\administrator\rl\tensorforce\tensorforce\models\pg_model.py", line 95, in init
 requires_deterministic=False
 File "c:\users\administrator\rl\tensorforce\tensorforce\models\distribution_model.py", line 86, in init
 discount=discount
 File "c:\users\administrator\rl\tensorforce\tensorforce\models\memory_model.py", line 106, in init
 reward_preprocessing=reward_preprocessing
 File "c:\users\administrator\rl\tensorforce\tensorforce\models\model.py", line 200, in init
 self.setup()
 File "c:\users\administrator\rl\tensorforce\tensorforce\models\model.py", line 307, in setup
 self.initialize(custom_getter=custom_getter)
 File "c:\users\administrator\rl\tensorforce\tensorforce\models\pg_model.py", line 107, in initialize
 super(PGModel, self).initialize(custom_getter)
 File "c:\users\administrator\rl\tensorforce\tensorforce\models\distribution_model.py", line 93, in initialize
 kwargs=dict(summary_labels=self.summary_labels)
 File "c:\users\administrator\rl\tensorforce\tensorforce\core\networks\network.py", line 180, in from_spec
 kwargs=kwargs
 File "c:\users\administrator\rl\tensorforce\tensorforce\util.py", line 159, in get_object
 return obj(*args, **kwargs)
 File "C:\Users\Administrator\RL\tforce_btc_trader\hypersearch.py", line 155, in init
 super(CustomNet, self).init(layers_spec, **kwargs)
 File "c:\users\administrator\rl\tensorforce\tensorforce\core\networks\network.py", line 270, in init
 kwargs=dict(scope=scope, summary_labels=summary_labels)
 File "c:\users\administrator\rl\tensorforce\tensorforce\core\networks\layer.py", line 143, in from_spec
 kwargs=kwargs
 File "c:\users\administrator\rl\tensorforce\tensorforce\util.py", line 159, in get_object
 return obj(*args, **kwargs)
 TypeError: init() got an unexpected keyword argument 'cell_clip'

**Comment by lefnire** [comment]
It's a tforce_btc_trader thing, we'll address it there

**Comment by michaelschaarschmidt** [comment]
yes, agree
