### ISSUE TITLE
Some issues when using the latest version of tensorforce

### ISSUE THREAD

**Issue by dmuestc** [reinforceio/tensorforce#362]
Hi all,

Thanks for open-sourcing this repository. It's really an amazing work!  we‘re actually trying  to handle some practical applications by tensorforce.  Recently, The memory branch has been merged into master branch, and get really a boost in training speed.
But it seems has some issues of the new version as follows:

**1. DQN / n-step DQN doesn't converge;**
I use the configs in example/configs dir, here:
[dqn.json](https://github.com/reinforceio/tensorforce/blob/master/examples/configs/dqn.json)
 [network.json](https://github.com/reinforceio/tensorforce/blob/master/examples/configs/mlp2_network.json)
 --I also try the configs in [tensorforce-benchmark](https://github.com/reinforceio/tensorforce-benchmark/blob/master/configs/dqn_cartpole.json), still didn't work.

**2. prioritized buffer seems not be ready?**
    self.memory.update_batch(loss_per_instance=loss_per_instance)
  File "/Users/sam/SoftDevlop/anaconda/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 278, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/Users/sam/SoftDevlop/anaconda/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/Users/sam/sam.dm/RL/Tensorforce/tensorforce/tensorforce/core/memories/prioritized_replay.py", line 402, in tf_update_batch
    priority_indices=priority_indices
  File "/Users/sam/sam.dm/RL/Tensorforce/tensorforce/tensorforce/core/memories/prioritized_replay.py", line 353, in tf_retrieve_indices
    assert util.rank(priority_indices) == 1
AssertionError:

**3. A exception throws running TRPO；**
Traceback (most recent call last):
  File "examples/openai_gym.py", line 140, in <module>
    main()
  File "examples/openai_gym.py", line 132, in main
    episode_finished=episode_finished
  File "/Users/sam/sam.dm/RL/Tensorforce/tensorforce/tensorforce/execution/runner.py", line 112, in run
    self.agent.observe(terminal=terminal, reward=reward)
  File "/Users/sam/sam.dm/RL/Tensorforce/tensorforce/tensorforce/agents/agent.py", line 226, in observe
    reward=self.observe_reward
  File "/Users/sam/sam.dm/RL/Tensorforce/tensorforce/tensorforce/models/model.py", line 1242, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/Users/sam/SoftDevlop/anaconda/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/Users/sam/SoftDevlop/anaconda/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/Users/sam/SoftDevlop/anaconda/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/sam/SoftDevlop/anaconda/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1024, in run
    run_metadata=run_metadata)
  File "/Users/sam/SoftDevlop/anaconda/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 827, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/sam/SoftDevlop/anaconda/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Users/sam/SoftDevlop/anaconda/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/sam/SoftDevlop/anaconda/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/Users/sam/SoftDevlop/anaconda/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

**Comment by michaelschaarschmidt** [comment]
Hi,
thank you for raising these points.
1. Note that these are just generic configs and may need to be tuned for your problem.
2. Yes prioritized replay is under construction, I might add an error message when using it currently to avoid this.
3. Will have to check separately at some point. Let me just  say there is usually no good reason to use TRPO vs PPO as PPO seems to be empirically superior.

**Comment by dmuestc** [comment]
thanks @michaelschaarschmidt , for the question one, my test env is CartPole-v0, and tried some configs and parameter tuning, but didn't work, so I guess some thing wrong with the config or a bug in the latest code?

**Comment by michaelschaarschmidt** [comment]
Hard to say without trying, will have to benchmark myself when i get to it

**Comment by dmuestc** [comment]
Yes, it's true. fine, I'll try more configs.

----------------------------------

Besides, I find maybe a bug in the environment states_spec, 
OpenAI-Gym env [here](https://github.com/reinforceio/tensorforce/blob/e3375b4d6a3df3b17f2b508ab58d9260d430f8c5/tensorforce/contrib/openai_gym.py#L90) and ALE env [here](https://github.com/reinforceio/tensorforce/blob/e3375b4d6a3df3b17f2b508ab58d9260d430f8c5/tensorforce/contrib/ale.py#L114).
In case of OOM when running Atari, such case set `states_spec[type'] = 'uint8'` will save more space, and scale-to-float could be done after sampling from memory.

**Comment by AndreasMegatranus** [comment]
I am running into a problem where the call to agent.observe in runner.py is hanging after 10 episodes.  Very weird.  Has anyone else run into this?

**Comment by MachineLearnerKA** [comment]
Yes, I have the same problem like @AndreasMegatranus. I have updated to the latest tensorforce version (0.4.2) and I am using the TRPOAgent. My program is running until terminal is set to True and agent.observe(reward=xy, terminal = True) is called. The Error message I get is:

Traceback (most recent call last):
  File "<input>", line 924, in make_decisions
  File "C:\Users\LSS\PycharmProjects\JMA\Simulation_PPS.py", line 146, in get_decision
    order, destination = self.learning_litho(possible_actions, Werker)
  File "C:\Users\LSS\PycharmProjects\JMA\Simulation_PPS.py", line 452, in learning_litho
    from Simulation_Main import env, stocks,machines, print_states, controller, print_possible_actions
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\LSS\PycharmProjects\JMA\Simulation_Main.py", line 1282, in <module>
    env.run(until = controller.m)
  File "C:\Users\LSS\AppData\Local\Programs\Python\Python36\lib\site-packages\simpy\core.py", line 137, in run
    self.step()
  File "C:\Users\LSS\AppData\Local\Programs\Python\Python36\lib\site-packages\simpy\core.py", line 227, in step
    exc = type(event._value)(*event._value.args)
TypeError: __init__() missing 3 required positional arguments: 'node_def', 'op', and 'message'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1282, in <module>
  File "C:\Users\LSS\AppData\Local\Programs\Python\Python36\lib\site-packages\simpy\core.py", line 137, in run
    self.step()
  File "C:\Users\LSS\AppData\Local\Programs\Python\Python36\lib\site-packages\simpy\core.py", line 229, in step
    raise exc
TypeError: __init__() missing 3 required positional arguments: 'node_def', 'op', and 'message'

**Comment by AndreasMegatranus** [comment]
I don't actually get a crash;  it just hangs in agent.observe.  Also, it doesn't hang until the 10th episode.  Very strange.
