### ISSUE TITLE
Invalidad Argument Error : has inputs from different frames

### ISSUE THREAD

**Issue by Giezzy** [reinforceio/tensorforce#376]
After last update (Tensorforce 0.4.0) seems that the Dropout layer has broken.
This issue is similar as https://github.com/reinforceio/tensorforce/issues/317 but in this case normal Dropout layers after a Dense are not working.

The Agent configuration used to be:

> agent = PPOAgent(
    states=dict(type='float', shape=(len(OBSERVATION_VARIABLES),)),
    actions=dict(type='int', num_actions=len(ACTION_MEANINGS)),
    network=[
        dict(type="internal_lstm", size=32, dropout=0.5),
        dict(type='dense', size=64),
        dict(type='dropout', rate=0.50),
        dict(type='dense', size=64),
        dict(type='dropout', rate=0.50),
    ],
    batching_capacity=500,
    step_optimizer=dict(
        type='adam',
        learning_rate=1e-4
    ),
    baseline_mode = "network",
    baseline=dict(type='mlp', sizes=[128,128]),
    baseline_optimizer=baseline_optimizer,
    discount=DISCOUNT,
    states_preprocessing=preprocessing_config,
    likelihood_ratio_clipping=0.15
)`

But after the update the code breaks after filling the batch capacity. This issue is solved if I removed the Dropout layers.

Error code as follows:

> Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-per-instance/apply/apply_2/cond/dropout/div_grad/Shape/Switch' has inputs from different frames. The input 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-per-instance/apply/apply_2/cond/dropout/Shape/Switch' is in frame 'ppo/observe-timestep/cond/optimization/multi-step/step/while/while_context'. The input 'ppo/observe-timestep/LogicalAnd_2' is in frame ''.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tensorforce_classes.py", line 293, in <module>
    main()
  File "tensorforce_classes.py", line 267, in main
    agent.observe(reward=reward, terminal=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorforce/agents/agent.py", line 226, in observe
    reward=self.observe_reward
  File "/usr/local/lib/python3.5/dist-packages/tensorforce/models/model.py", line 1256, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 539, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1104, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1089, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1161, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 941, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: The node 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/gradients/ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-per-instance/apply/apply_2/cond/dropout/div_grad/Shape/Switch' has inputs from different frames. The input 'ppo/observe-timestep/cond/optimization/multi-step/step/while/step/step/loss/loss-per-instance/apply/apply_2/cond/dropout/Shape/Switch' is in frame 'ppo/observe-timestep/cond/optimization/multi-step/step/while/while_context'. The input 'ppo/observe-timestep/LogicalAnd_2' is in frame ''.

**Comment by lefnire** [comment]
See #317

**Comment by michaelschaarschmidt** [comment]
Closing as duplicate
