### ISSUE TITLE
Bug: Model.start_server called twice in distributed mode

### ISSUE THREAD

**Issue by Wellan89** [reinforceio/tensorforce#386]
The workers cannot start in distributed mode since the `Model.start_server` method is called twice per worker (with the same ports, one time for the local model and another time for the global one).

Here is the traceback I get when printing `self.distributed_spec` in `model.py:376`:
```
> CUDA_VISIBLE_DEVICES= /home/destygo/.pyenv/versions/perso/bin/python /home/destygo/rl/rl-board/train_async.py csb-d4-v0 --agent /home/destygo/rl/rl-board/agents/trpo-v1b.json --network /home/destygo/rl/rl-board/networks/mlp-v1b.json --num-workers 2 --child --task-index 1

/home/destygo/.pyenv/versions/perso/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
{'job': 'worker', 'protocol': 'grpc', 'task_index': 1, 'cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7febcdbc3668>}
2018-04-02 16:46:51.360324: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job ps -> {0 -> 127.0.0.1:12222}
2018-04-02 16:46:51.360342: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:215] Initialize GrpcChannelCache for job worker -> {0 -> 127.0.0.1:12223, 1 -> localhost:12224}
2018-04-02 16:46:51.360563: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:324] Started server with target: grpc://localhost:12224
{'job': 'worker', 'protocol': 'grpc', 'task_index': 1, 'cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7febd0dd9860>}
E0402 16:46:55.104458972   14708 server_chttp2.cc:38]        {"created":"@1522680415.104410071","description":"No address added out of total 1 resolved","file":"external/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":248,"referenced_errors":[{"created":"@1522680415.104408716","description":"Failed to add any wildcard listeners","file":"external/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":340,"referenced_errors":[{"created":"@1522680415.104399671","description":"Unable to configure socket","fd":10,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":200,"referenced_errors":[{"created":"@1522680415.104386644","description":"OS Error","errno":98,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":173,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1522680415.104408391","description":"Unable to configure socket","fd":10,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":200,"referenced_errors":[{"created":"@1522680415.104406673","description":"OS Error","errno":98,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":173,"os_error":"Address already in use","syscall":"bind"}]}]}]}
Traceback (most recent call last):
  File "/home/destygo/rl/rl-board/train_async.py", line 176, in <module>
    main()
  File "/home/destygo/rl/rl-board/train_async.py", line 171, in main
    task_index=args.task_index,
  File "/home/destygo/rl/rl-board/train_utils.py", line 104, in do_train
    seconds=120)
  File "/home/destygo/rl/tensorforce/tensorforce/agents/agent.py", line 241, in from_spec
    kwargs=kwargs
  File "/home/destygo/rl/tensorforce/tensorforce/util.py", line 175, in get_object
    return obj(*args, **kwargs)
  File "/home/destygo/rl/tensorforce/tensorforce/agents/trpo_agent.py", line 158, in __init__
    entropy_regularization=entropy_regularization
  File "/home/destygo/rl/tensorforce/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/home/destygo/rl/tensorforce/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/home/destygo/rl/tensorforce/tensorforce/agents/trpo_agent.py", line 186, in initialize_model
    likelihood_ratio_clipping=self.likelihood_ratio_clipping
  File "/home/destygo/rl/tensorforce/tensorforce/models/pg_prob_ratio_model.py", line 88, in __init__
    gae_lambda=gae_lambda
  File "/home/destygo/rl/tensorforce/tensorforce/models/pg_model.py", line 98, in __init__
    requires_deterministic=False
  File "/home/destygo/rl/tensorforce/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/home/destygo/rl/tensorforce/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/destygo/rl/tensorforce/tensorforce/models/model.py", line 220, in __init__
    self.setup()
  File "/home/destygo/rl/tensorforce/tensorforce/models/model.py", line 233, in setup
    self.start_server()
  File "/home/destygo/rl/tensorforce/tensorforce/models/model.py", line 383, in start_server
    start=True
  File "/home/destygo/.pyenv/versions/perso/lib/python3.5/site-packages/tensorflow/python/training/server_lib.py", line 145, in __init__
    self._server_def.SerializeToString(), status)
  File "/home/destygo/.pyenv/versions/perso/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Could not start gRPC server
```

Also in `examples/openai_gym_async.py`, the `agent['execution']` block should be changed to:
```
    agent['execution'] = dict(
        type='distributed',
        distributed_spec=dict(
            cluster_spec=cluster_spec,
            task_index=args.task_index,
            job='ps' if args.parameter_server else 'worker',
            protocol='grpc'
        )
    )
```
(parameter_server became job)

**Comment by michaelschaarschmidt** [comment]
should be fixed now
