### ISSUE TITLE
InvalidArgumentError 

### ISSUE THREAD

**Issue by tennenboke** [reinforceio/tensorforce#390]
When I run the example:ale_threaded_ale.py, I use 4 threads to the module, but it cann't work.So I changed the number 4 to 1, unfortunately, it still terminated excepedly. 
Starting DQNAgent for Environment 'ALE(breakout.bin)'
========================================
Current Step/Episode: 1071/5
SPS: 1069.18577881
========================================
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/zhanglinjing/tensorforce/tensorforce/execution/threaded_runner.py", line 225, in _run_single
    agent.observe(reward=reward, terminal=terminal)
  File "/home/zhanglinjing/tensorforce/tensorforce/agents/agent.py", line 176, in observe
    reward=self.observe_reward
  File "/home/zhanglinjing/tensorforce/tensorforce/models/model.py", line 1343, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1170, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 950, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
InvalidArgumentError: Must have updates.shape = indices.shape + params.shape[1:], got updates.shape [1000,84,84,1], indices.shape [168], params.shape [1000000,84,84,1]
	 [[Node: dqn/observe-timestep/store/ScatterUpdate = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@dqn/initialize/replay/initialize/state-state"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dqn/initialize/replay/initialize/state-state, dqn/observe-timestep/store/mod, dqn/strided_slice, ^dqn/observe-timestep/store/AssignSub)]]

Caused by op u'dqn/observe-timestep/store/ScatterUpdate', defined at:
  File "threaded_ale.py", line 192, in <module>
    main()
  File "threaded_ale.py", line 119, in main
    network=network_spec
  File "/home/zhanglinjing/tensorforce/tensorforce/agents/agent.py", line 241, in from_spec
    kwargs=kwargs
  File "/home/zhanglinjing/tensorforce/tensorforce/util.py", line 175, in get_object
    return obj(*args, **kwargs)
  File "/home/zhanglinjing/tensorforce/tensorforce/agents/dqn_agent.py", line 131, in __init__
    entropy_regularization=entropy_regularization
  File "/home/zhanglinjing/tensorforce/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/home/zhanglinjing/tensorforce/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/home/zhanglinjing/tensorforce/tensorforce/agents/dqn_agent.py", line 158, in initialize_model
    huber_loss=self.huber_loss
  File "/home/zhanglinjing/tensorforce/tensorforce/models/q_model.py", line 98, in __init__
    requires_deterministic=True
  File "/home/zhanglinjing/tensorforce/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/home/zhanglinjing/tensorforce/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/zhanglinjing/tensorforce/tensorforce/models/model.py", line 220, in __init__
    self.setup()
  File "/home/zhanglinjing/tensorforce/tensorforce/models/model.py", line 273, in setup
    independent=independent
  File "/home/zhanglinjing/tensorforce/tensorforce/models/memory_model.py", line 607, in create_operations
    independent=independent
  File "/home/zhanglinjing/tensorforce/tensorforce/models/model.py", line 1100, in create_operations
    self.create_observe_operations(reward=reward, terminal=terminal)
  File "/home/zhanglinjing/tensorforce/tensorforce/models/model.py", line 1078, in create_observe_operations
    reward=reward
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 464, in __call__
    result = self._call_func(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 406, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/zhanglinjing/tensorforce/tensorforce/models/memory_model.py", line 507, in tf_observe_timestep
    reward=reward
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 455, in __call__
    result = self._call_func(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/template.py", line 400, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/zhanglinjing/tensorforce/tensorforce/core/memories/queue.py", line 172, in tf_store
    updates=state
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 356, in scatter_update
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 984, in scatter_update
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Must have updates.shape = indices.shape + params.shape[1:], got updates.shape [1000,84,84,1], indices.shape [168], params.shape [1000000,84,84,1]
	 [[Node: dqn/observe-timestep/store/ScatterUpdate = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, _class=["loc:@dqn/initialize/replay/initialize/state-state"], use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dqn/initialize/replay/initialize/state-state, dqn/observe-timestep/store/mod, dqn/strided_slice, ^dqn/observe-timestep/store/AssignSub)]]

**Comment by michaelschaarschmidt** [comment]
Hello,
this error is because of state/action vs reward counters being out of sync, I don't know when I will have time to fix the threaded runner, but hope at some point soon

**Comment by tennenboke** [comment]
Thanks for your reply, I will continue to pay attention to this issue and look forward to fixing the issue.

**Comment by michaelschaarschmidt** [comment]
Closing this -> discussion and my comments on whats causing it here https://github.com/reinforceio/tensorforce/issues/384
