### ISSUE TITLE
TRPO failing after a few iterations of training

### ISSUE THREAD

**Issue by FitMachineLearning** [reinforceio/tensorforce#398]
I have the following code

`import gym
import numpy as np
from tensorforce.agents import PPOAgent
from tensorforce.agents import TRPOAgent
#from tensorforce import Configuration

NUM_GAMES_TO_PLAY = 70000
MAX_MEMORY_LEN = 100000
CLIP_ACTION = False

env = gym.make("CartPole-v0")
# Create a Proximal Policy Optimization agent
#actions=dict(type='float', shape=(2,)),

agent = TRPOAgent(
    states=dict(type='float32', shape=(4,)),
    actions=dict(type='int', num_actions=2),
    network=[
        dict(type='dense', size=32,activation='relu'),
        dict(type='dense', size=32,activation='relu'),
        dict(type='dense', size=32,activation='relu')
    ],

    update_mode=dict(
        unit='episodes',
        batch_size=4,
        frequency=4
    ),
    memory=dict(
        type='latest',
        include_next_states=False,
        capacity=100
    ),
    learning_rate=1e-2

)

'''
    batching_capacity=200,
    step_optimizer=dict(
        type='adadelta',
        learning_rate=1e-3)
'''

allRewards = np.zeros(shape=(1,1))

for game in range(NUM_GAMES_TO_PLAY):
    obs = env.reset()
    gameTotalReward = 0
    for step in range(1000):
        env.render()
        a = agent.act(obs)
        #print("ACTION ->",a)
        if CLIP_ACTION:
            for i in range (np.alen(a)):
                if a[i] < -1: a[i]=-0.99999999999
                if a[i] > 1: a[i] = 0.99999999999
        obs, reward, done, info = env.step(a)
        #reward = reward/100
        gameTotalReward = gameTotalReward + reward
        allRewards = np.vstack((allRewards, np.array([reward])))
        if done:
            agent.observe(reward=reward, terminal=True)
        else:
            agent.observe(reward=reward, terminal=False)

        #print("Action: {} Observations Size:{} score: {}".format(a,obs.shape,reward))
        if done:
            print("#",game," last game average ", (gameTotalReward/step)*100,"recent avg", allRewards.flatten()[-10000:].mean()*100,"global avg", allRewards.mean()*100, "max",allRewards.max()*100,"min",allRewards.min()*100 , "steps", step)
            if np.alen(allRewards) >= MAX_MEMORY_LEN:
                allRewards = allRewards[1200:]
            break
`

However after a few episodes I get the following error.

# 0  last game average  102.63157894736842 recent avg 97.5 global avg 97.5 max 100.0 min 0.0 steps 38
# 1  last game average  112.5 recent avg 97.95918367346938 global avg 97.95918367346938 max 100.0 min 0.0 steps 8
# 2  last game average  112.5 recent avg 98.27586206896551 global avg 98.27586206896551 max 100.0 min 0.0 steps 8
Traceback (most recent call last):
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CartPole_TForce_PPO.py", line 65, in <module>
    agent.observe(reward=reward, terminal=True)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 176, in observe
    reward=self.observe_reward
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorforce/models/model.py", line 1343, in observe
    episode = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 521, in run
    run_metadata=run_metadata)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 967, in run
    raise six.reraise(*original_exc_info)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1024, in run
    run_metadata=run_metadata)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 827, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/Users/eljed/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value
Eljeds-iMac:SpaceX eljed$

**Comment by michaelschaarschmidt** [comment]
Is this latest tensorflow?

**Comment by andreaspasternak** [comment]
Can you please properly format your code? Then I could also read it and potentially help you.

**Comment by AlexKuhnle** [comment]
Is this still a problem?
