### ISSUE TITLE
Can you explain why the following DDPG code errors out.

### ISSUE THREAD

**Issue by FitMachineLearning** [reinforceio/tensorforce#400]
import gym
import numpy as np
import tensorforce
from tensorforce.agents import PPOAgent,TRPOAgent,DDPGAgent
#from tensorforce import Configuration

NUM_GAMES_TO_PLAY = 70000
CLIP_ACTIONS = False #set to true if you want actions to be clipped between [-1,1]

env = gym.make("CartPole-v0")
print("Observations ", env.observation_space, " Actions",env.action_space)

network_config = [{"type": "dense", "size": 64, "activation": "tanh"},
                  {"type": "dense", "size": 64, "activation": "tanh"}]
network_specs  =[
    dict(type='dense', size=32),
    dict(type='dense', size=32),
    dict(type='dense', size=32)
]
critic_network_specs  =[
    dict(type='dense', size=32),
    dict(type='dense', size=32),
    dict(type='dense', size=32)
]
agent = DDPGAgent(states=dict(type='float32', shape=(4,)),
                    actions=dict(type='int', num_actions=2),
                    network=network_specs,
                    update_mode={
                        "unit": "timesteps",
                        "batch_size": 64,
                        "frequency": 64
                    },
                    memory = {
                        "type": "replay",
                        "capacity": 100000,
                        "include_next_states": True
                    },
                    optimizer = {
                        "type": "adam",
                        "learning_rate": 1e-4
                    },
                    discount = 0.99,
                    entropy_regularization = None,
                    critic_network = {
                        "size_t0": 64,
                        "size_t1": 64
                    },
                    critic_optimizer = {
                        "type": "adam",
                        "learning_rate": 1e-3
                    },
                    target_sync_frequency = 1,
                    target_update_weight = 0.999,
                    actions_exploration = {
                        "type": "ornstein_uhlenbeck",
                        "sigma": 0.3,
                        "mu": 0.0,
                        "theta": 0.15
                    },
                    execution = {
                        "type": "single",
                        "session_config": None,
                        "distributed_spec": None
                    }

                    )

allRewards = np.zeros(shape=(1,1))

for game in range(NUM_GAMES_TO_PLAY):
    obs = env.reset()
    gameTotalReward = 0
    for step in range(1000):
        env.render()
        a = agent.act(obs)
        #print("ACTION ->",a)
        if CLIP_ACTIONS:
            for i in range (np.alen(a)):
                if a[i] < -1: a[i]=-0.99999999999
                if a[i] > 1: a[i] = 0.99999999999
        obs, reward, done, info = env.step(a)
        #reward = reward/100
        gameTotalReward = gameTotalReward + reward
        allRewards = np.vstack((allRewards, np.array([reward])))
        if done:
            agent.observe(reward=reward, terminal=True)
        else:
            agent.observe(reward=reward, terminal=False)

        #print("Action: {} Observations Size:{} score: {}".format(a,obs.shape,reward))
        if done:
            print("#",game," last game average ", (gameTotalReward/step)*100,"global avg", allRewards.mean()*100, "max",allRewards.max()*100,"min",allRewards.min()*100 , "steps", step)

            break

============

The code above gives the following error

============

Observations  Box(4,)  Actions Discrete(2)
Traceback (most recent call last):
  File "C:\Project\SpaceXRocket\cartpole_test_2_.py", line 64, in <module>
    "distributed_spec": None
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\agents\ddpg_agent.py", line 140, in __init__
    entropy_regularization=entropy_regularization
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\agents\learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\agents\agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\agents\ddpg_agent.py", line 167, in initialize_model
    target_update_weight=self.target_update_weight
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\dpg_target_model.py", line 166, in __init__
    requires_deterministic=True
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\distribution_model.py", line 90, in __init__
    discount=discount
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\model.py", line 220, in __init__
    self.setup()
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\model.py", line 273, in setup
    independent=independent
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\memory_model.py", line 607, in create_operations
    independent=independent
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\model.py", line 1100, in create_operations
    self.create_observe_operations(reward=reward, terminal=terminal)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\model.py", line 1078, in create_observe_operations
    reward=reward
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\template.py", line 278, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\memory_model.py", line 526, in tf_observe_timestep
    batch = self.memory.retrieve_timesteps(n=batch_size)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\template.py", line 278, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\core\memories\replay.py", line 91, in tf_retrieve_timesteps
    false_fn=resample_fn
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorflow\python\util\deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1864, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 1725, in BuildCondBranch
    original_result = fn()
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\core\memories\replay.py", line 83, in resample_fn
    maximum_iterations=10
TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'

originally defined at:
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\model.py", line 249, in setup
    self.setup_components_and_tf_funcs()
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\dpg_target_model.py", line 173, in setup_components_and_tf_funcs
    custom_getter = super(DPGTargetModel, self).setup_components_and_tf_funcs(custom_getter)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\distribution_model.py", line 119, in setup_components_and_tf_funcs
    custom_getter = super(DistributionModel, self).setup_components_and_tf_funcs(custom_getter)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\memory_model.py", line 141, in setup_components_and_tf_funcs
    summary_labels=self.summary_labels
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\core\memories\memory.py", line 196, in from_spec
    kwargs=kwargs
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\util.py", line 175, in get_object
    return obj(*args, **kwargs)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\core\memories\replay.py", line 48, in __init__
    summary_labels=summary_labels
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\core\memories\queue.py", line 59, in __init__
    summary_labels=summary_labels
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\core\memories\memory.py", line 59, in __init__
    self.setup_template_funcs()
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\core\memories\queue.py", line 63, in setup_template_funcs
    custom_getter = super(Queue, self).setup_template_funcs(custom_getter=custom_getter)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\core\memories\memory.py", line 84, in setup_template_funcs
    custom_getter_=custom_getter

originally defined at:
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\model.py", line 249, in setup
    self.setup_components_and_tf_funcs()
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\dpg_target_model.py", line 173, in setup_components_and_tf_funcs
    custom_getter = super(DPGTargetModel, self).setup_components_and_tf_funcs(custom_getter)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\distribution_model.py", line 119, in setup_components_and_tf_funcs
    custom_getter = super(DistributionModel, self).setup_components_and_tf_funcs(custom_getter)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\memory_model.py", line 132, in setup_components_and_tf_funcs
    custom_getter = super(MemoryModel, self).setup_components_and_tf_funcs(custom_getter)
  File "C:\Users\maka\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\tensorforce\models\model.py", line 527, in setup_components_and_tf_funcs
    custom_getter_=custom_getter

**Comment by krfricke** [comment]
First, please explain your problem instead of just dumping an error log.

Second, please crop the error log to only include the relevant part.

Third, you're using tensorflow <= 1.4. Tensorforce is currently compatible with tensorflow >= 1.6 - just upgrade tensorflow (preferably to 1.7) and that error should be gone.
