### ISSUE TITLE
PPO Baseline with Complex Networks

### ISSUE THREAD

**Issue by andreaspasternak** [reinforceio/tensorforce#401]
Hello all,

I am using a `PPOAgent` with complex networks. If I disable baselines the code works. But I could not figure out how to get baselines to work. I want to use my value function as the baseline, so I guess I need to use network baseline.

This are my states:
```
    @property
    def states(self):
        print "getting states"
        return dict(laser=dict(type='float', shape=(512,)),
                    velocities=dict(type='float', shape=(2,)))
```

This my code (simplified, to get it running):

```

network_spec = [[
    dict(type='input', inputs=['velocities']),
    dict(type='dense', size=128),
    dict(type='output', output='prediction')

]]

agent = PPOAgent(
    states=environment.states,
    actions=environment.actions,
    network=network_spec,
    # Agent
    states_preprocessing=None,
    actions_exploration=None,
    reward_preprocessing=None,
    # MemoryModel
    update_mode=dict(
        unit='episodes',
        # 10 episodes per update
        batch_size=10,
        # Every 10 episodes
        frequency=10
    ),
    memory=dict(
        type='latest',
        include_next_states=False,
        capacity=5000
    ),
    # DistributionModel
    distributions=None,
    entropy_regularization=0.01,
    # PGModel
    baseline_mode='network',
    baseline=dict(
        type='custom',
        network=network_spec

    ),
    baseline_optimizer=dict(
        type='multi_step',
        optimizer=dict(
            type='adam',
            learning_rate=0.5e-3
        ),
        num_steps=5
    ),
    gae_lambda=0.97,
    # PGLRModel
    likelihood_ratio_clipping=0.2,
    # PPOAgent
    step_optimizer=dict(
        type='adam',
        learning_rate=0.5e-3
    ),
    subsampling_fraction=0.2,
    optimization_steps=25,
    execution=dict(
        type='single',
        session_config=None,
        distributed_spec=None
    ),

)
```

This is the error message:
```
Traceback (most recent call last):
  File "/home/andreas.pasternak/deeplearning/simulation/catkin_ws/src/argos_bridge/scripts/argosAgent.py", line 140, in <module>
    distributed_spec=None
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/agents/ppo_agent.py", line 155, in __init__
    entropy_regularization=entropy_regularization
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/agents/ppo_agent.py", line 183, in initialize_model
    likelihood_ratio_clipping=self.likelihood_ratio_clipping
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/pg_prob_ratio_model.py", line 88, in __init__
    gae_lambda=gae_lambda
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/pg_model.py", line 98, in __init__
    requires_deterministic=False
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/model.py", line 220, in __init__
    self.setup()
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/model.py", line 273, in setup
    independent=independent
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/memory_model.py", line 607, in create_operations
    independent=independent
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/model.py", line 1100, in create_operations
    self.create_observe_operations(reward=reward, terminal=terminal)
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/model.py", line 1078, in create_observe_operations
    reward=reward
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 464, in __call__
    result = self._call_func(args, kwargs)
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 406, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/memory_model.py", line 567, in tf_observe_timestep
    false_fn=tf.no_op
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2047, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1897, in BuildCondBranch
    original_result = fn()
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/memory_model.py", line 566, in <lambda>
    true_fn=(lambda: self.fn_optimization(**batch)),
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 464, in __call__
    result = self._call_func(args, kwargs)
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 406, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/pg_model.py", line 293, in tf_optimization
    update=tf.constant(value=True)
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 464, in __call__
    result = self._call_func(args, kwargs)
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 406, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/models/pg_model.py", line 173, in tf_reward_estimation
    update=update
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 464, in __call__
    result = self._call_func(args, kwargs)
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 406, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/core/baselines/network_baseline.py", line 50, in tf_predict
    embedding = self.network.apply(x=states, internals=internals, update=update)
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 464, in __call__
    result = self._call_func(args, kwargs)
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 406, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/core/networks/complex_network.py", line 190, in tf_apply
    x = layer.apply(x=x, update=update)
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 464, in __call__
    result = self._call_func(args, kwargs)
  File "/home/andreas.pasternak/.local/lib/python2.7/site-packages/tensorflow/python/ops/template.py", line 406, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/andreas.pasternak/deeplearning/tensorforce/tensorforce/core/networks/complex_network.py", line 71, in tf_apply
    'ComplexNetwork input "{}" doesn\'t exist, Available inputs: {}'.format(name, keys)
tensorforce.exception.TensorForceError: ComplexNetwork input "velocities" doesn't exist, Available inputs: []
```

Thank you so much!

**Comment by michaelschaarschmidt** [comment]
Did you get it to run?  A quickfix would be to just merge your states into one flat input. Complex networks were a contributed class that isnt fully integrated into the baselines..
