### ISSUE TITLE
Error running the example

### ISSUE THREAD

**Issue by soupault** [reinforceio/tensorforce#41]
```
[egor@host tensorforce]$ python examples/openai_gym.py CartPole-v0 -a TRPOAgent -c examples/configs/trpo_cartpole.json -n examples/configs/trpo_cartpole_network.json -s /home/egor/Software/tensorforce/examples/output
[2017-07-19 00:35:06,206] Making new env: CartPole-v0
2017-07-19 00:35:06.922073: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-19 00:35:06.922107: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-19 00:35:06.922116: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-19 00:35:06.922128: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-19 00:35:06.922135: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
[2017-07-19 00:35:06,977] Starting TRPOAgent for Environment 'OpenAIGym(CartPole-v0)'
[2017-07-19 00:35:08,600] Finished episode 50 after 12 timesteps
[2017-07-19 00:35:08,600] Episode reward: 12.0
[2017-07-19 00:35:08,600] Average of last 500 rewards: 2.332
[2017-07-19 00:35:08,600] Average of last 100 rewards: 11.66
Saving agent after episode 100
Traceback (most recent call last):
  File "examples/openai_gym.py", line 121, in <module>
    main()
  File "examples/openai_gym.py", line 112, in main
    runner.run(args.episodes, args.max_timesteps, episode_finished=episode_finished)
  File "/home/egor/Software/tensorforce/tensorforce/execution/runner.py", line 158, in run
    self.agent.save_model(self.save_path)
  File "/home/egor/Software/tensorforce/tensorforce/agents/agent.py", line 238, in save_model
    self.model.save_model(path)
  File "/home/egor/Software/tensorforce/tensorforce/models/model.py", line 274, in save_model
    self.saver.save(self.session, path)
AttributeError: 'NoneType' object has no attribute 'save'
```

**Comment by michaelschaarschmidt** [comment]
Hi, 

sorry about that, there is an inconsistency with the --save flag currently regarding the creation of a saver. We are in the process of overhauling model import/export. 

You should be able to run the example if you leave the --save flag empty and just run the example as is (or run the test for the example). We will fix this soon.

**Comment by soupault** [comment]
@michaelschaarschmidt yes, I confirm that it works without specifying `--save`. From a quick look, the issue is somewhere on a model level.
Thanks!

**Comment by michaelschaarschmidt** [comment]
Yep, we are on that now: https://github.com/reinforceio/tensorforce/issues/42
