### ISSUE TITLE
ValueError: low >= high

### ISSUE THREAD

**Issue by bching28** [reinforceio/tensorforce#418]
```
Traceback (most recent call last):
  File "range_finder.py", line 336, in <module>
    main()
  File "range_finder.py", line 102, in main
    reachTen(stepper)
  File "range_finder.py", line 162, in reachTen
    action = stepper.choice([curr_sum, rand_num, cs_bool, r_bool])
  File "/home/bching/git/relsat/choice_function/stepper.py", line 131, in choice
    self.observe(terminal=terminal, reward=self.total_step_rewards)
  File "/home/bching/git/relsat/choice_function/stepper.py", line 98, in observe
    self.agent.observe(terminal=terminal, reward=reward)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/agents/memory_agent.py", line 136, in observe
    batch = self.memory.get_batch(batch_size=self.batch_size, next_states=True)
  File "/home/bching/.local/lib/python2.7/site-packages/tensorforce/core/memories/replay.py", line 81, in get_batch
    indices = np.random.randint(self.size - 1, size=batch_size)
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high
```

I noticed that I am getting this error when I am loading a pre-trained model and the agent completes the run within one iteration. I did some digging around and I noticed that it was an issue with line 81 in replay.py. In my case, `self.size` is equal to 1 by the time it reaches line 81, and then you subtract 1 from that when you pass it into `np.random.randint`. In other words, you are passing in a value of 0 into `np.random.randint`, which throws that ValueError.

The work around I found was to remove the "-1" from the code. So essentially, the code on line 81 is now:
`indices = np.random.randint(self.size - 1, size=batch_size)`
However, I am wondering, will that cause any other issues with saving and loading models?

**Comment by AlexKuhnle** [comment]
Any news on that, does it work in more recent versions?

**Comment by AlexKuhnle** [comment]
Assuming it is fixed then...
