### ISSUE TITLE
distributed mode with saver failed.

### ISSUE THREAD

**Issue by lynic** [reinforceio/tensorforce#445]
tensorforce: master
tensorflow: 1.5.1

```
INFO:tensorflow:Create CheckpointSaverHook.                                    
2018-07-06 18:34:39,815 - tensorflow - INFO - Create CheckpointSaverHook.      
ERROR:tensorflow:Multiple tensors in global_step collection.                   
2018-07-06 18:34:42,905 - tensorflow - ERROR - Multiple tensors in global_step collection.                                                                     
Traceback (most recent call last):     
  File "/home/elynn/Documents/source/elynn/tensorforce/examples/openai_gym_async.py", line 245, in <module>                                                        main()                             
  File "/home/elynn/Documents/source/elynn/tensorforce/examples/openai_gym_async.py", line 202, in main                                                        
    network=network                    
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/agents/agent.py", line 283, in from_spec                                                    
    kwargs=kwargs                      
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/util.py", line 192, in get_object                                                           
    return obj(*args, **kwargs)        
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/agents/ppo_agent.py", line 155, in __init__                                                 
    entropy_regularization=entropy_regularization                              
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/agents/learning_agent.py", line 141, in __init__                                            
    batching_capacity=batching_capacity                                        
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/agents/agent.py", line 80, in __init__                                                      
    self.model = self.initialize_model()                                       
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/agents/ppo_agent.py", line 183, in initialize_model                                         
    likelihood_ratio_clipping=self.likelihood_ratio_clipping                   
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/models/pg_prob_ratio_model.py", line 88, in __init__                                        
    gae_lambda=gae_lambda              
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/models/pg_model.py", line 98, in __init__                                                   
    requires_deterministic=False       
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/models/distribution_model.py", line 90, in __init__                                         
    discount=discount                  
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/models/memory_model.py", line 114, in __init__                                              
    reward_preprocessing=reward_preprocessing                                  
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/models/model.py", line 223, in __init__                                                     
    self.setup()                       
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/models/model.py", line 312, in setup                                                        
    self.setup_session(self.server, hooks, graph_default_context)              
  File "/home/elynn/Documents/source/elynn/tensorforce/tensorforce/models/model.py", line 740, in setup_session                                                
    stop_grace_period_secs=120  # Default value.                               
  File "/home/elynn/anaconda3/envs/stockforce/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 787, in __init__              
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/elynn/anaconda3/envs/stockforce/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 504, in __init__
    h.begin()
  File "/home/elynn/anaconda3/envs/stockforce/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 422, in begin
    "Global step should be created to use CheckpointSaverHook.")
RuntimeError: Global step should be created to use CheckpointSaverHook.
```

**Comment by AlexKuhnle** [comment]
Sorry for the late reply, just getting started with support again. I'll try to look into that soon.

**Comment by AlexKuhnle** [comment]
Could you post the config, please?

**Comment by AlexKuhnle** [comment]
Does this still happen with the latest commits? Alternatively, does it still happen if you update TensorFlow (or downgrade to 1.5.0)? I can't really reproduce the error...

**Comment by AlexKuhnle** [comment]
Assuming this is solved. Reopen if not...
