### ISSUE TITLE
Prioritized replay index out-of-range

### ISSUE THREAD

**Issue by mryellow** [reinforceio/tensorforce#45]
```
Traceback (most recent call last):
  File "examples/openai_gym.py", line 121, in <module>
    main()
  File "examples/openai_gym.py", line 112, in main
    runner.run(args.episodes, args.max_timesteps, episode_finished=episode_finished)
  File "/home/yellow/work/tf/tensorforce/tensorforce/execution/runner.py", line 144, in run
    self.agent.observe(reward=reward, terminal=terminal)
  File "/home/yellow/work/tf/tensorforce/tensorforce/agents/dqn_agent.py", line 94, in observe
    super(DQNAgent, self).observe(reward=reward, terminal=terminal)
  File "/home/yellow/work/tf/tensorforce/tensorforce/agents/memory_agent.py", line 84, in observe
    internal=self.current_internal
  File "/home/yellow/work/tf/tensorforce/tensorforce/core/memories/prioritized_replay.py", line 55, in add_observation
    priority, _ = self.observations.pop(self.positive_priority_index)
IndexError: pop index out of range
```

**Comment by mryellow** [comment]
`print(len(self.observations), self.positive_priority_index)`

`10000 -10001`

**Comment by michaelschaarschmidt** [comment]
thanks for bringing it up, will fix this weekend!

**Comment by AlexKuhnle** [comment]
It should be fixed now.
