### ISSUE TITLE
examples/openai_gym_async.py issue 

### ISSUE THREAD

**Issue by saddy001** [reinforceio/tensorforce#463]
I've got a freshly cloned git copy of tensorforce and tried to run the A3C example on Cartpole. 
When running for the first time, it could not find my gpu, but when commenting out the line
> 'CUDA_VISIBLE_DEVICES=',

It found one (Same when setting it to 1). Unfortunately, the clients got a problem too. Here's the stacktrace:
```
saddy@dsksdy:~/Programme/tensorforce$ /home/saddy/miniconda3/bin/python /home/saddy/Programme/tensorforce/examples/openai_gym_async.py CartPole-v0 --agent /home/saddy/Programme/tensorforce/examples/configs/vpg.json --network /home/saddy/Programme/tensorforce/examples/configs/mlp2_network.json --num-workers 3 --child --task-index 2 --episodes 10000 --max-episode-timesteps 200
/home/saddy/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
2018-07-30 20:48:25.539739: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2018-07-30 20:48:25.638203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6575
pciBusID: 0000:17:00.0
totalMemory: 10.91GiB freeMemory: 32.69MiB
2018-07-30 20:48:25.638228: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
Traceback (most recent call last):
  File "/home/saddy/Programme/tensorforce/examples/openai_gym_async.py", line 247, in <module>
    main()
  File "/home/saddy/Programme/tensorforce/examples/openai_gym_async.py", line 204, in main
    network=network
  File "/home/saddy/Programme/tensorforce/tensorforce/agents/agent.py", line 283, in from_spec
    kwargs=kwargs
  File "/home/saddy/Programme/tensorforce/tensorforce/util.py", line 192, in get_object
    return obj(*args, **kwargs)
  File "/home/saddy/Programme/tensorforce/tensorforce/agents/vpg_agent.py", line 136, in __init__
    entropy_regularization=entropy_regularization
  File "/home/saddy/Programme/tensorforce/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/home/saddy/Programme/tensorforce/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/home/saddy/Programme/tensorforce/tensorforce/agents/vpg_agent.py", line 163, in initialize_model
    gae_lambda=self.gae_lambda
  File "/home/saddy/Programme/tensorforce/tensorforce/models/pg_model.py", line 98, in __init__
    requires_deterministic=False
  File "/home/saddy/Programme/tensorforce/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/home/saddy/Programme/tensorforce/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/saddy/Programme/tensorforce/tensorforce/models/model.py", line 217, in __init__
    self.setup()
  File "/home/saddy/Programme/tensorforce/tensorforce/models/model.py", line 230, in setup
    self.start_server()
  File "/home/saddy/Programme/tensorforce/tensorforce/models/model.py", line 408, in start_server
    start=True
  File "/home/saddy/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/server_lib.py", line 147, in __init__
    self._server_def.SerializeToString(), status)
  File "/home/saddy/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory
```
My card has 12GB RAM, isn't that enough for this small example?

The cmd was
> python examples/openai_gym_async.py CartPole-v0 -a examples/configs/vpg.json -n examples/configs/mlp2_network.json -e 10000 -m 200 -W 3

**Comment by AlexKuhnle** [comment]
The only explanation I can think of from the top of my head is that providing a custom `session_config` [value](https://www.tensorflow.org/versions/r1.8/api_docs/python/tf/ConfigProto) may help. Check out the [available values](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/core/protobuf/config.proto), where a parameter `per_process_gpu_memory_fraction` can adjust the memory usage. I assume that the first worker (or ps already) blocks 100% of the memory by default. Don't have much experience with GPUs and async execution, unfortunately.

**Comment by saddy001** [comment]
If I'm interpreting this correctly it's one of (?) the children (--child) that's consuming the memory:
```
$ nvidia-smi 
Tue Jul 31 16:01:05 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.77                 Driver Version: 390.77                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:17:00.0  On |                  N/A |
| 28%   60C    P2    60W / 280W |  10635MiB / 11175MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1602      G   /usr/lib/xorg/Xorg                           129MiB |
|    0      3960      G   /usr/bin/nvidia-settings                       0MiB |
|    0      4795      C   /home/saddy/miniconda3/bin/python          10493MiB |
+-----------------------------------------------------------------------------+

$ nvidia-smi pmon
# gpu        pid  type    sm   mem   enc   dec   command
# Idx          #   C/G     %     %     %     %   name
    0       1602     G     0     0     0     0   Xorg           
    0       3960     G     0     0     0     0   nvidia-settings
    0       4795     C     0     0     0     0   python         

$ ps aux|grep 4795
saddy     4795  2.5  6.8 30890972 1106816 pts/0 Sl+ 16:00   0:04 /home/saddy/miniconda3/bin/python /home/saddy/Programme/tensorforce/examples/openai_gym_async.py CartPole-v0 --agent /home/saddy/Programme/tensorforce/examples/configs/vpg.json --network /home/saddy/Programme/tensorforce/examples/configs/mlp2_network.json --num-workers 3 --child --task-index 0 --episodes 10000 --max-episode-timesteps 200 --parameter-server
```

**Comment by saddy001** [comment]
The A3C paper states that this algorithm is CPU only, which explains the
> 'CUDA_VISIBLE_DEVICES='

It get's stuck, but that's another issue.

**Comment by AlexKuhnle** [comment]
Where is this line `'CUDA_VISIBLE_DEVICES='` from? If you're using the parameter mentioned above, I would expect it to work, or otherwise you can of course run it on CPU.

**Comment by saddy001** [comment]
It's line 102 in examples/openai_gym_async.py

**Comment by saddy001** [comment]
I think it explicitly prevents the gpu from being used.

**Comment by AlexKuhnle** [comment]
Will remove it, shouldn't really be the case...

**Comment by saddy001** [comment]
Really? I thought that https://arxiv.org/pdf/1602.01783.pdf is describing openai_gym_async.py

**Comment by AlexKuhnle** [comment]
It's following the same distributed execution setup, but it was not intended to constrain other aspects as well. CPU/GPU can be set via `device`, and the same script can also be used for Q-models, for instance (although it doesn't make as much sense to do so).
