### ISSUE TITLE
Incompatible type conversion requested to type 'int64' for variable of type 'int32_ref'

### ISSUE THREAD

**Issue by davidhopper2003** [reinforceio/tensorforce#474]
A data type conversion error occurred when I ran the sample program with the command `python examples/openai_gym.py CartPole-v0 -a examples/configs/dqn.json -n examples/configs/mlp2_network.json -e 2000 -m 200`:

```
/home/davidhopper/code/gym/gym/__init__.py:22: UserWarning: DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.
  warnings.warn('DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.')
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/davidhopper/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/__main__.py", line 211, in <module>
    singlesession=args.single_session)
  File "/home/davidhopper/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/__main__.py", line 205, in main
    debug_main(addr, name, kind, *extra, **kwargs)
  File "/home/davidhopper/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 30, in debug_main
    run_file(address, name, *extra, **kwargs)
  File "/home/davidhopper/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 64, in run_file
    run(argv, addr, **kwargs)
  File "/home/davidhopper/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 125, in _run
    _pydevd.main()
  File "/home/davidhopper/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1699, in main
    debugger.connect(host, port)
  File "/home/davidhopper/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1061, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/davidhopper/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1068, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/davidhopper/.vscode/extensions/ms-python.python-2018.7.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/davidhopper/code/tensorforce/examples/openai_gym.py", line 172, in <module>
    main()
  File "/home/davidhopper/code/tensorforce/examples/openai_gym.py", line 104, in main
    network=network,
  File "/home/davidhopper/code/tensorforce/tensorforce/agents/agent.py", line 283, in from_spec
    kwargs=kwargs
  File "/home/davidhopper/code/tensorforce/tensorforce/util.py", line 192, in get_object
    return obj(*args, **kwargs)
  File "/home/davidhopper/code/tensorforce/tensorforce/agents/dqn_agent.py", line 131, in __init__
    entropy_regularization=entropy_regularization
  File "/home/davidhopper/code/tensorforce/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/home/davidhopper/code/tensorforce/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/home/davidhopper/code/tensorforce/tensorforce/agents/dqn_agent.py", line 158, in initialize_model
    huber_loss=self.huber_loss
  File "/home/davidhopper/code/tensorforce/tensorforce/models/q_model.py", line 98, in __init__
    requires_deterministic=True
  File "/home/davidhopper/code/tensorforce/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/home/davidhopper/code/tensorforce/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/davidhopper/code/tensorforce/tensorforce/models/model.py", line 217, in __init__
    self.setup()
  File "/home/davidhopper/code/tensorforce/tensorforce/models/model.py", line 290, in setup
    independent=independent
  File "/home/davidhopper/code/tensorforce/tensorforce/models/memory_model.py", line 605, in create_operations
    independent=independent
  File "/home/davidhopper/code/tensorforce/tensorforce/models/model.py", line 1195, in create_operations
    self.create_observe_operations(reward=reward, terminal=terminal)
  File "/home/davidhopper/code/tensorforce/tensorforce/models/model.py", line 1129, in create_observe_operations
    reward=reward
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 427, in __call__
    return self._call_func(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 370, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/davidhopper/code/tensorforce/tensorforce/models/memory_model.py", line 566, in tf_observe_timestep
    return tf.cond(pred=optimize, true_fn=true_fn, false_fn=tf.no_op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2040, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1890, in BuildCondBranch
    original_result = fn()
  File "/home/davidhopper/code/tensorforce/tensorforce/models/memory_model.py", line 562, in true_fn
    optimize = self.fn_optimization(**batch)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 427, in __call__
    return self._call_func(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 370, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/davidhopper/code/tensorforce/tensorforce/models/q_model.py", line 256, in tf_optimization
    target_optimization = self.target_optimizer.minimize(**arguments)
  File "/home/davidhopper/code/tensorforce/tensorforce/core/optimizers/optimizer.py", line 139, in minimize
    deltas = self.step(time=time, variables=variables, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 427, in __call__
    return self._call_func(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 370, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/davidhopper/code/tensorforce/tensorforce/core/optimizers/synchronization.py", line 92, in tf_step
    do_sync = (time - last_sync >= self.sync_frequency)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 826, in _run_op
    return getattr(ops.Tensor, operator)(a._AsTensor(), *args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 850, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1011, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1107, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 798, in _TensorConversionFunction
    "of type '%s'" % (dtype.name, v.dtype.name))
ValueError: Incompatible type conversion requested to type 'int64' for variable of type 'int32_ref'

originally defined at:
  File "/home/davidhopper/code/tensorforce/tensorforce/models/model.py", line 245, in setup
    self.setup_components_and_tf_funcs()
  File "/home/davidhopper/code/tensorforce/tensorforce/models/q_model.py", line 128, in setup_components_and_tf_funcs
    self.target_optimizer = Optimizer.from_spec(spec=self.target_optimizer_spec)
  File "/home/davidhopper/code/tensorforce/tensorforce/core/optimizers/optimizer.py", line 160, in from_spec
    kwargs=kwargs
  File "/home/davidhopper/code/tensorforce/tensorforce/util.py", line 192, in get_object
    return obj(*args, **kwargs)
  File "/home/davidhopper/code/tensorforce/tensorforce/core/optimizers/synchronization.py", line 48, in __init__
    super(Synchronization, self).__init__(scope=scope, summary_labels=summary_labels)
  File "/home/davidhopper/code/tensorforce/tensorforce/core/optimizers/optimizer.py", line 52, in __init__
    custom_getter=custom_getter
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 153, in make_template
    **kwargs)
```
Is there a solution? Thanks a lot.

**Comment by daggertye** [comment]
#470

It should work now.

**Comment by davidhopper2003** [comment]
@daggertye 
I downloaded the latest code. it's OK now. Thank you.
