### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by wm901115nwpu** [reinforceio/tensorforce#487]
python examples/openai_gym.py CartPole-v0 -a examples/configs/ppo.json -n examples/configs/mlp2_network.json

I counter a problem:
Traceback (most recent call last):
  File "examples/openai_gym.py", line 33, in <module>
    from tensorforce.agents import Agent
  File "/home/wangmeng/tensorforce/tensorforce/agents/__init__.py", line 16, in <module>
    from tensorforce.agents.agent import Agent
  File "/home/wangmeng/tensorforce/tensorforce/agents/agent.py", line 24, in <module>
    from tensorforce import util, TensorForceError
  File "/home/wangmeng/tensorforce/tensorforce/util.py", line 19, in <module>
    import tensorflow as tf
  File "/home/wangmeng/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "/home/wangmeng/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/wangmeng/.local/lib/python2.7/site-packages/tensorflow/python/framework/framework_lib.py", line 102, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/wangmeng/.local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 32, in <module>
    from tensorflow.python.framework import function
  File "/home/wangmeng/.local/lib/python2.7/site-packages/tensorflow/python/framework/function.py", line 37, in <module>
    from tensorflow.python.ops import resource_variable_ops
  File "/home/wangmeng/.local/lib/python2.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 35, in <module>
    from tensorflow.python.ops import variables
  File "/home/wangmeng/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 40, in <module>
    class Variable(checkpointable.CheckpointableBase):
AttributeError: 'module' object has no attribute 'CheckpointableBase'

**Comment by AlexKuhnle** [comment]
Are you using the latest version of both TensorFlow? That looks very much like a problem with TensorFlow or something not-TensorForce-related, given where the error occurs:
```
File "/home/wangmeng/tensorforce/tensorforce/util.py", line 19, in 
import tensorflow as tf
```
