### ISSUE TITLE
Exception on init agent with states preprocessing

### ISSUE THREAD

**Issue by Gor-Ren** [reinforceio/tensorforce#493]
Running off of the latest commit at time of writing cee7873, we can run the following basic example based off the tutorial script to init a PPO agent with state preprocessing:

```python
import numpy as np
from tensorforce.agents import PPOAgent
from tensorforce.execution import Runner
from tensorforce.contrib.openai_gym import OpenAIGym


# Create an OpenAIgym environment
env = OpenAIGym('LunarLanderContinuous-v2', visualize=False)

# Network as list of layers
network_spec = [
    dict(type='dense', size=32, activation='tanh'),
    dict(type='dense', size=32, activation='tanh')
]

states_preprocessing = [dict(type='running_standardize')]

agent = PPOAgent(
    states=env.states,
    actions=env.actions,
    network=network_spec,
    states_preprocessing=states_preprocessing
)
```

It throws with the stack trace pasted below.

The error is not thrown when using TensorForce 4.3 from PyPI so the problem must have been introduced within the ~11 commits since then.

```
Traceback (most recent call last):
  File "/home/gordon/dev/aircraft-rl/tests/test_init_ppo_agent.py", line 30, in <module>
    states_preprocessing=states_preprocessing
  File "/home/gordon/dev/tensorforce/tensorforce/agents/ppo_agent.py", line 155, in __init__
    entropy_regularization=entropy_regularization
  File "/home/gordon/dev/tensorforce/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/home/gordon/dev/tensorforce/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/home/gordon/dev/tensorforce/tensorforce/agents/ppo_agent.py", line 183, in initialize_model
    likelihood_ratio_clipping=self.likelihood_ratio_clipping
  File "/home/gordon/dev/tensorforce/tensorforce/models/pg_prob_ratio_model.py", line 88, in __init__
    gae_lambda=gae_lambda
  File "/home/gordon/dev/tensorforce/tensorforce/models/pg_model.py", line 98, in __init__
    requires_deterministic=False
  File "/home/gordon/dev/tensorforce/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/home/gordon/dev/tensorforce/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 218, in __init__
    self.setup()
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 284, in setup
    states, actions, reward = self.fn_preprocess(states=states, actions=actions, reward=reward)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 464, in __call__
    result = self._call_func(args, kwargs)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 406, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 919, in tf_preprocess
    states[name] = self.states_preprocessing[name].process(tensor=states[name])
  File "/home/gordon/dev/tensorforce/tensorforce/core/preprocessors/preprocessor.py", line 136, in process
    tensor = processor.process(tensor=tensor)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 464, in __call__
    result = self._call_func(args, kwargs)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 406, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/gordon/dev/tensorforce/tensorforce/core/preprocessors/running_standardize.py", line 53, in tf_process
    trainable=False
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1317, in get_variable
    constraint=constraint)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1079, in get_variable
    constraint=constraint)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 417, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1720, in wrapped_custom_getter
    *args, **kwargs)
  File "/home/gordon/dev/tensorforce/tensorforce/core/preprocessors/preprocessor.py", line 49, in custom_getter
    assert kwargs.get('trainable', False)
AssertionError: 

originally defined at:
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 243, in setup
    self.setup_placeholders()
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 473, in setup_placeholders
    kwargs=dict(shape=self.states_spec[name]['shape'])
  File "/home/gordon/dev/tensorforce/tensorforce/core/preprocessors/preprocessor.py", line 170, in from_spec
    kwargs=preprocessor_kwargs
  File "/home/gordon/dev/tensorforce/tensorforce/util.py", line 192, in get_object
    return obj(*args, **kwargs)
  File "/home/gordon/dev/tensorforce/tensorforce/core/preprocessors/running_standardize.py", line 42, in __init__
    super(RunningStandardize, self).__init__(shape=shape, scope=scope, summary_labels=summary_labels)
  File "/home/gordon/dev/tensorforce/tensorforce/core/preprocessors/preprocessor.py", line 56, in __init__
    custom_getter_=custom_getter
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 153, in make_template
    **kwargs)


originally defined at:
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 246, in setup
    self.setup_components_and_tf_funcs()
  File "/home/gordon/dev/tensorforce/tensorforce/models/pg_model.py", line 110, in setup_components_and_tf_funcs
    custom_getter = super(PGModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/gordon/dev/tensorforce/tensorforce/models/distribution_model.py", line 120, in setup_components_and_tf_funcs
    custom_getter = super(DistributionModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/gordon/dev/tensorforce/tensorforce/models/memory_model.py", line 132, in setup_components_and_tf_funcs
    custom_getter = super(MemoryModel, self).setup_components_and_tf_funcs(custom_getter)
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 565, in setup_components_and_tf_funcs
    custom_getter_=custom_getter
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 153, in make_template
    **kwargs)
```

**Comment by AlexKuhnle** [comment]
You're right, stupid little bug in one of the later commits, but hopefully works with the update I just committed.
