### ISSUE TITLE
PPO agent throws exception when using exploration

### ISSUE THREAD

**Issue by Gor-Ren** [reinforceio/tensorforce#494]
I'm seeing PPO agents throwing exceptions when I try to use OU exploration noise. This occurs both with TensorForce built from latest commit cee7873 and 4.3 from PyPI. 

Minimal example based on tutorial script:

```python
import numpy as np
from tensorforce.agents import PPOAgent
from tensorforce.execution import Runner
from tensorforce.contrib.openai_gym import OpenAIGym


# Create an OpenAIgym environment
env = OpenAIGym('LunarLanderContinuous-v2', visualize=False)

# Network as list of layers
network_spec = [
    dict(type='dense', size=32, activation='tanh'),
    dict(type='dense', size=32, activation='tanh')
]


exploration = dict(
    type='ornstein_uhlenbeck',
    sigma=0.3,
    mu=0.0,
    theta=0.15
)

agent = PPOAgent(
    states=env.states,
    actions=env.actions,
    network=network_spec,
    actions_exploration=exploration,
)


# Create the runner
runner = Runner(agent=agent, environment=env)


# Callback function printing episode statistics
def episode_finished(r):
    print("Finished episode {ep} after {ts} timesteps (reward: {reward})".format(ep=r.episode, ts=r.episode_timestep,
                                                                                 reward=r.episode_rewards[-1]))
    return True


# Start learning
runner.run(episodes=3000, max_episode_timesteps=200, episode_finished=episode_finished)
runner.close()

# Print statistics
print("Learning finished. Total episodes: {ep}. Average reward of last 100 episodes: {ar}.".format(
    ep=runner.episode,
    ar=np.mean(runner.episode_rewards[-100:]))
)
``` 

The exception thrown (see below) looks an awful lot like issue #399 for DDPG in continuous action spaces, possibly they have a similar cause? @AlexKuhnle you recently fixed the DDPG issue... I don't suppose this might be a quick and easy fix for you? I looked around the PG model classes to find where shapes were set to attempt my own fix, but no dice. I would dearly like to try some exploration to improve results before a deadline I have approaching! :)

```
Traceback (most recent call last):
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnimplementedError: sliced l-value shape [1,2] does not match r-value shape [2,2]. Automatic broadcasting not yet implemented.
	 [[Node: ppo/cond_1/ppo/cond_1/strided_slice_2/_assign = StridedSliceAssign[Index=DT_INT32, T=DT_FLOAT, _class=["loc:@ppo/initialize/action-action"], begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/cond_1/ppo/cond_1/strided_slice_2/_assign/Switch, ppo/cond_1/strided_slice_2/stack, ppo/cond_1/strided_slice_2/stack_1, ppo/cond_1/strided_slice_2/stack_2, ppo/cond_1/ppo/cond_1/strided_slice_2/_assign/Switch_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gordon/dev/aircraft-rl/tests/test_init_ppo_agent.py", line 48, in <module>
    runner.run(episodes=3000, max_episode_timesteps=200, episode_finished=episode_finished)
  File "/home/gordon/dev/tensorforce/tensorforce/execution/runner.py", line 102, in run
    action = self.agent.act(states=state, deterministic=deterministic)
  File "/home/gordon/dev/tensorforce/tensorforce/agents/agent.py", line 148, in act
    independent=independent
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 1413, in act
    fetch_list = self.monitored_session.run(fetches=fetches, feed_dict=feed_dict)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 567, in run
    run_metadata=run_metadata)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1134, in run
    raise six.reraise(*original_exc_info)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1119, in run
    return self._sess.run(*args, **kwargs)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1191, in run
    run_metadata=run_metadata)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 971, in run
    return self._sess.run(*args, **kwargs)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: sliced l-value shape [1,2] does not match r-value shape [2,2]. Automatic broadcasting not yet implemented.
	 [[Node: ppo/cond_1/ppo/cond_1/strided_slice_2/_assign = StridedSliceAssign[Index=DT_INT32, T=DT_FLOAT, _class=["loc:@ppo/initialize/action-action"], begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/cond_1/ppo/cond_1/strided_slice_2/_assign/Switch, ppo/cond_1/strided_slice_2/stack, ppo/cond_1/strided_slice_2/stack_1, ppo/cond_1/strided_slice_2/stack_2, ppo/cond_1/ppo/cond_1/strided_slice_2/_assign/Switch_1)]]

Caused by op 'ppo/cond_1/ppo/cond_1/strided_slice_2/_assign', defined at:
  File "/home/gordon/dev/aircraft-rl/tests/test_init_ppo_agent.py", line 31, in <module>
    actions_exploration=exploration,
  File "/home/gordon/dev/tensorforce/tensorforce/agents/ppo_agent.py", line 155, in __init__
    entropy_regularization=entropy_regularization
  File "/home/gordon/dev/tensorforce/tensorforce/agents/learning_agent.py", line 141, in __init__
    batching_capacity=batching_capacity
  File "/home/gordon/dev/tensorforce/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/home/gordon/dev/tensorforce/tensorforce/agents/ppo_agent.py", line 183, in initialize_model
    likelihood_ratio_clipping=self.likelihood_ratio_clipping
  File "/home/gordon/dev/tensorforce/tensorforce/models/pg_prob_ratio_model.py", line 88, in __init__
    gae_lambda=gae_lambda
  File "/home/gordon/dev/tensorforce/tensorforce/models/pg_model.py", line 98, in __init__
    requires_deterministic=False
  File "/home/gordon/dev/tensorforce/tensorforce/models/distribution_model.py", line 90, in __init__
    discount=discount
  File "/home/gordon/dev/tensorforce/tensorforce/models/memory_model.py", line 114, in __init__
    reward_preprocessing=reward_preprocessing
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 218, in __init__
    self.setup()
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 293, in setup
    independent=independent
  File "/home/gordon/dev/tensorforce/tensorforce/models/memory_model.py", line 605, in create_operations
    independent=independent
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 1214, in create_operations
    independent=independent
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 1114, in create_act_operations
    false_fn=normal_act
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2072, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1913, in BuildCondBranch
    original_result = fn()
  File "/home/gordon/dev/tensorforce/tensorforce/models/model.py", line 1093, in normal_act
    value=self.actions_output[name]
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 284, in assign
    return ref.assign(value, name=name)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 786, in assign
    shrink_axis_mask=shrink_axis_mask)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 693, in _strided_slice_assign
    shrink_axis_mask=shrink_axis_mask)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8267, in strided_slice_assign
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/gordon/dev/aircraft-rl/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnimplementedError (see above for traceback): sliced l-value shape [1,2] does not match r-value shape [2,2]. Automatic broadcasting not yet implemented.
	 [[Node: ppo/cond_1/ppo/cond_1/strided_slice_2/_assign = StridedSliceAssign[Index=DT_INT32, T=DT_FLOAT, _class=["loc:@ppo/initialize/action-action"], begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/cond_1/ppo/cond_1/strided_slice_2/_assign/Switch, ppo/cond_1/strided_slice_2/stack, ppo/cond_1/strided_slice_2/stack_1, ppo/cond_1/strided_slice_2/stack_2, ppo/cond_1/ppo/cond_1/strided_slice_2/_assign/Switch_1)]]
```

**Comment by AlexKuhnle** [comment]
The latest commit should fix this issue. The shape handling for exploration was actually in general quite problematic / inconsistent.

**Comment by Gor-Ren** [comment]
Confirmed working, thanks again!
