### ISSUE TITLE
'RandomModel' object has no attribute 'action_spec'

### ISSUE THREAD

**Issue by Deathn0t** [reinforceio/tensorforce#496]
Hi, I am having this error when running with a RandomAgent.

My code :
```
[...]
agent = RandomAgent(
    states=environment.states,
    actions=environment.actions
)
[...]
```

Stacktrace :
```
Traceback (most recent call last):
  File "/Users/Deathn0t/Desktop/tensorforce-0.4.3/tests/rdm_mathfun.py", line 48, in <module>
    # Create the runner
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorforce/agents/random_agent.py", line 73, in __init__
    batching_capacity=batching_capacity
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 80, in __init__
    self.model = self.initialize_model()
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorforce/agents/random_agent.py", line 85, in initialize_model
    batching_capacity=self.batching_capacity
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorforce/models/random_model.py", line 54, in __init__
    reward_preprocessing=None
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorforce/models/model.py", line 217, in __init__
    self.setup()
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorforce/models/model.py", line 290, in setup
    independent=independent
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorforce/models/model.py", line 1193, in create_operations
    independent=independent
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorforce/models/model.py", line 1019, in create_act_operations
    deterministic=deterministic
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 464, in __call__
    result = self._call_func(args, kwargs)
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 406, in _call_func
    result = self._func(*args, **kwargs)
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorforce/models/random_model.py", line 62, in tf_actions_and_internals
    action = self.action_spec[name]
AttributeError: 'RandomModel' object has no attribute 'action_spec'

originally defined at:
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorforce/models/model.py", line 245, in setup
    self.setup_components_and_tf_funcs()
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorforce/models/model.py", line 546, in setup_components_and_tf_funcs
    custom_getter_=custom_getter
  File "/Users/Deathn0t/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 153, in make_template
    **kwargs)
```

**Comment by AlexKuhnle** [comment]
Just fixed it, due to a minor typo.
