### ISSUE TITLE
Terminal state update error

### ISSUE THREAD

**Issue by mansilla** [reinforceio/tensorforce#533]
Hi I have declared an agent like this

``` python
agent = PPOAgent(
        states=dict(type='float', shape=(37,)),
        actions=dict(type='int', num_actions=3),
        network=[
            dict(type='dense', size=74),
            dict(type='dense', size=31)
        ],
        batching_capacity=1200,
        step_optimizer=dict(
            type='adam',
            learning_rate=1e-4
        ),
        summarizer=dict(
            directory="./board",
            steps=50,
            labels=['graph',
                'losses',
                'total-loss']
        )
    )
```
everything work when I do: `agent.observe(reward=reward, terminal=False)`, but the following error shows up on: `agent.observe(reward=reward, terminal=True)`

``` shell
InvalidArgumentError (see above for traceback): Must have updates.shape = indices.shape + params.shape[1:] or updates.shape = [], got updates.shape [60,37], indices.shape [35], params.shape [10000,37]
	 [[node ppo/observe-timestep/store/ScatterUpdate (defined at /venv/lib/python3.6/site-packages/tensorforce/core/memories/queue.py:176)  = ScatterUpdate[T=DT_FLOAT, Tindices=DT_INT32, use_locking=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ppo/initialize/latest/initialize/state-state, ppo/observe-timestep/store/mod, ppo/strided_slice, ^ppo/observe-timestep/store/AssignSub)]]
```
It seems to be an error with the shapes dimensions. But I haven't managed to understand the logic behind this shape arithmetic: `updates.shape = indices.shape + params.shape[1:]`
Can you explain it please?

**Comment by AlexKuhnle** [comment]
Hi,
The shape arithmetic is from the TensorFlow exception and shows which shapes don't fit together why. A likely cause for this is if you do not call `observe()` after every call to `act()`. Is that possible? Otherwise, could you post the code where you interact with the agent (`act()` and `observe()`)?

**Comment by AlexKuhnle** [comment]
That code looks alright. What error did you get with `Runner`, out of interest? Generally, are you using the newest version of TensorFlow and Tensorforce (GitHub version)?

**Comment by mansilla** [comment]
Hey, I have just replicated the `Runner` object error.
``` python
Traceback (most recent call last):
  File "agent.v1.0.py", line 104, in <module>
    main(e+1)
  File "agent.v1.0.py", line 90, in main
    runner.run(episodes=3000, max_episode_timesteps=200, episode_finished=episode_finished)
  File "/venv/lib/python3.6/site-packages/tensorforce/execution/runner.py", line 100, in run
    action = self.agent.act(states=state, deterministic=deterministic)
  File "/venv/lib/python3.6/site-packages/tensorforce/agents/agent.py", line 148, in act
    independent=independent
  File "/venv/lib/python3.6/site-packages/tensorforce/models/model.py", line 1373, in act
    assert state.shape[0] <= self.batching_capacity
IndexError: tuple index out of range
```
The weird thing here is that I have a "debug" message in my `env.get_state` function, showing the shape of the state, but it never was printed. As if this `assert state.shape[0] <= self.batching_capacity` was called before the first `env.get_state` call. Also I modify the `model.py` and tried to print the cuestioned shape but I got `()`. Here's the source using `Runner` (with the example code provided in the website)

``` python
agent = PPOAgent(
        states=dict(type='float', shape=(37,)),
        actions=dict(type='int', num_actions=3),
        network=[
            dict(type='dense', size=74),
            dict(type='dense', size=31)
        ],
        batching_capacity=1200,
        step_optimizer=dict(
            type='adam',
            learning_rate=1e-4
        ),
        summarizer=dict(
            directory="./board",
            steps=50,
            labels=['graph',
                'losses',
                'total-loss']
        )
    )

    try:
        agent.restore_model("./checkpoints/")
    except Exception as e:
        logging.info("> error restoring model:"+str(e))


    # Create the runner
    runner = Runner(agent=agent, environment=env)


    # Callback function printing episode statistics
    def episode_finished(r):
        print("Finished episode {ep} after {ts} timesteps (reward: {reward})".format(ep=r.episode, ts=r.episode_timestep,
                                                                                    reward=r.episode_rewards[-1]))
        return True


    # Start learning
    runner.run(episodes=3000, max_episode_timesteps=200, episode_finished=episode_finished)
    runner.close()

    # Print statistics
    print("Learning finished. Total episodes: {ep}. Average reward of last 100 episodes: {ar}.".format(
        ep=runner.episode,
        ar=np.mean(runner.episode_rewards[-100:]))
    )
```

**Comment by mansilla** [comment]
I'm using the `pip` repository version. Let me pull the TensorForce source from Github and see if that works.

**Comment by mansilla** [comment]
I can confirm the bug was resolved when updating to the Github version. Thanks for all. Closing the thread.
